### ISSUE TITLE
"no more connections allowed (max_client_conn)" is reported while no clients connected at all

### ISSUE THREAD

**Issue by bashtanov** [pgbouncer/pgbouncer#140] opened 2016-07-18 10:49 UTC
I have seen this bug on 1.5.4, 1.5.5, 1.6.1, 1.7rc1, 1.7, 1.7.2 and master (fdf5b8e) versions. Sometimes it takes several tries to reproduce it, especially on newer versions, but I've never spent more than 10 tries.
My system is linux ubuntu 14.04.
1. Install pgbouncer, configure it using config below, run it
2. run two consoles, execute the following in each of them: `for((;;)); do psql -p 6432 -At -c 'select pg_sleep(1)' >/dev/null; echo -n .; done`
3. press Ctrl+C in one of the consoles and hold it, patiently waiting for bash loop to finish (could take tens of seconds)
4. look at the other console: probably it is reporting "ERROR: no more connections allowed (max_client_conn)". It happens every time for 1.5, but once every 3-4 times on 1.7. Retry pp. 2-3 if necessary.
5. now we have a pgbouncer instance that has `max_client_conn = 99` in its config and does not accept connections at all

```
alexey = host=localhost dbname=alexey reserve_pool=0
[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = 127.0.0.1
listen_port = 6432
unix_socket_dir = /tmp
auth_type = trust
auth_file = /etc/pgbouncer/userlist.txt
admin_users = alexey
pool_mode = transaction
server_reset_query_always = 0
server_reset_query = 
max_client_conn = 99
default_pool_size = 2
```

**Comment by bashtanov** [comment] 2016-07-18 10:52
this applies to session pooling mode as well

**Comment by markokr** [comment] 2016-12-19 18:05
Interesting test case, but I don't see a bug here.

Seems the psql does not rate-limit cancel requests, so if your key repeat rate is high enough you can fill smallish max_client_conn before first req loops over postgres back to pgbouncer and psql.  And shell won't notice until psql eats those ^C-s.

Using max_client_conn to deal with connect-floods seems proper, so it seems pgbouncer functions as intended.

Closing.

**Closed by markokr** 2016-12-19 18:05 UTC

**Comment by zhonghuasheng** [comment] 2019-02-12 09:24
I meet this issue and I set a bigger value for max_client_conn to fixed it.
