### ISSUE TITLE
(bug or feature) In case of incorrect connection string "infinite" error in pgbouncer/postgresql logs >FATAL: database "*" does not exist

### ISSUE THREAD

**Issue by panaxtri** [pgbouncer/pgbouncer#975] opened 2023-10-30 12:24 UTC
**psql -h xxx -U yyu6576 -d fgh456 -p 6432**

**pgbouncer.ini**
```
[databases]
#reader1 = host=127.0.0.0.1 port=5432 # There will be no errors because the database is hard-coded.
* = host=127.0.0.1 port=5432 # In case of incorrect connection string there will be "infinite" error in pgbouncer logs >FATAL: database "fgh456" does not exist

[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /run/pgbouncer/pgbouncer.pid
listen_addr = *
listen_port = 6432
unix_socket_dir = /var/run/postgresql
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt
auth_user = ttt
```

**show databases;**
```
   name    |   host    | port | database  | force_user | pool_size | min_pool_size | reserve_pool | pool_mode | max_connections | current_connections | paused | disabled
-----------+-----------+------+-----------+------------+-----------+---------------+--------------+-----------+-----------------+---------------------+--------+----------
 fgh       | 127.0.0.1 | 5432 | fgh       |            |       200 |             5 |            5 |           |               0 |                   0 |      0 |        0
 fgh456    | 127.0.0.1 | 5432 | fgh456    |            |       200 |             5 |            5 |           |               0 |                   0 |      0 |        0
 pgbouncer |           | 6432 | pgbouncer | pgbouncer  |         2 |             0 |            0 | statement |               0 |                   0 |      0 |        0
```

**show clients;**
```
 type |   user   | database  |  state  |      addr      | port  |   local_addr   | local_port |      connect_time       |      request_time       | wait | wait_us | close_needed |    ptr    | link | remote_pid | tls | application_name
------+----------+-----------+---------+----------------+-------+----------------+------------+-------------------------+-------------------------+------+---------+--------------+-----------+------+------------+-----+------------------
 C    | (nouser) | fgh       | waiting | 192.172.23.182 | 37004 | 192.172.23.183 |       6432 | 2023-10-23 12:09:23 MSK | 2023-10-23 12:09:23 MSK |    0 |       0 |            0 | 0x1c6d950 |      |          0 |     | psql
 C    | (nouser) | fgh456    | waiting | 192.172.23.182 | 37094 | 192.172.23.183 |       6432 | 2023-10-23 12:10:07 MSK | 2023-10-23 12:10:07 MSK |    0 |       0 |            0 | 0x1c6de10 |      |          0 |     | psql
 C    | ttt     | pgbouncer | active  | 127.0.0.1      | 48706 | 127.0.0.1      |       6432 | 2023-10-23 12:09:40 MSK | 2023-10-23 12:10:23 MSK |   41 |  112169 |            0 | 0x1c6dbb0 |      |          0 |     | psql
(3 rows)
```
**show servers;**
```
 type | user | database | state | addr | port | local_addr | local_port | connect_time | request_time | wait | wait_us | close_needed | ptr | link | remote_pid | tls | application_name
------+------+----------+-------+------+------+------------+------------+--------------+--------------+------+---------+--------------+-----+------+------------+-----+------------------
(0 rows)
```

```
pgbouncer=# **show FDS;**
 fd |  task  | user | database |      addr      | port  | cancel | link | client_encoding | std_strings | datestyle | timezone | password | scram_client_key | scram_server_key
----+--------+------+----------+----------------+-------+--------+------+-----------------+-------------+-----------+----------+----------+------------------+------------------
  7 | pooler |      |          | 0.0.0.0        |  6432 |      0 |    0 |                 |             |           |          |          |                  |
  8 | pooler |      |          | ::             |  6432 |      0 |    0 |                 |             |           |          |          |                  |
  9 | client |      | fgh      | 192.172.23.182 | 37004 |      0 |    0 | UTF8            |             |           |          |          |                  |
 11 | client |      | fgh456   | 192.172.23.182 | 37094 |      0 |    0 | UTF8            |             |           |          |          |                  |
(4 rows)
```

**/var/log/postgres/1_Mon.log**
< 2023-10-23 12:16:41.665 MSK 11642 pgbouncer >FATAL:  database "fgh456" does not exist
< 2023-10-23 12:16:44.020 MSK 11654 pgbouncer >FATAL:  database "fgh" does not exist
< 2023-10-23 12:16:56.679 MSK 11704 pgbouncer >FATAL:  database "fgh456" does not exist
< 2023-10-23 12:16:59.347 MSK 11717 pgbouncer >FATAL:  database "fgh" does not exist
< 2023-10-23 12:17:12.005 MSK 11771 pgbouncer >FATAL:  database "fgh456" does not exist
< 2023-10-23 12:17:14.675 MSK 11782 pgbouncer >FATAL:  database "fgh" does not exist
< 2023-10-23 12:17:27.009 MSK 11831 pgbouncer >FATAL:  database "fgh456" does not exist
< 2023-10-23 12:17:29.661 MSK 11844 pgbouncer >FATAL:  database "fgh" does not exist
......

**Comment by eulerto** [comment] 2023-10-30 15:41
You didn't describe the whole picture. Does the referred databases (`fgh` or `fgh456`) exist in Postgres? You didn't mention the PgBouncer version. I would expect an error (using the latest version -- `1.20.1`) like

```
2023-10-30 12:27:44.365 -03 [17324] WARNING server login failed: FATAL database "xpto" does not exist
2023-10-30 12:27:44.365 -03 [17324] NOISE kill_pool_logins_server_error: sqlstate: 3D000
2023-10-30 12:27:44.365 -03 [17324] LOG C-0x55ad0a72d430: xpto/euler@unix(17452):6432 closing because: database "xpto" does not exist (age=0s)
2023-10-30 12:27:44.365 -03 [17324] WARNING C-0x55ad0a72d430: xpto/euler@unix(17452):6432 pooler error: database "xpto" does not exist
2023-10-30 12:27:44.365 -03 [17324] LOG S-0x55ad0a7347d0: xpto/euler@unix:9916 closing because: login failed (age=0s)
```

Since you are using `auth_user` the expected behavior is to use the pair `auth_user` and database name to connect to Postgres. If the database doesn't exist, the authentication is not possible so the client connection returns an error like

```
$ psql -p 6432 -d xpto
psql: error: connection to server on socket "/tmp/.s.PGSQL.6432" failed: FATAL:  database "xpto" does not exist
```

**Comment by panaxtri** [comment] 2023-10-30 16:08
1) PgBouncer 1.18.0

2) I also wanted to point out that the timeout for waiting for a query before it is canceled solves the problem >FATAL: database "fgh456" does not exist
# query_wait_timeout = 0
query_wait_timeout = 100 

3) The base fgh456 does not exist in the database in reality

The database fgh456 does not exist in the database in reality, but the user entering the wrong database name just hangs in waiting, and if query_wait_timeout =0 it will hang indefinitely, and if he breaks the connection to the database himself killing the client request (kill -p xxx) then show databases still shows the non-existent database + show clients shows that supposedly there is a client and even port supposedly shows, although in fact the connection is long gone.

**Comment by eulerto** [comment] 2023-10-30 17:13
Hmm. I think I understand what's going on. You didn't set `auth_file` so the authentication never ends. If you set `verbose = 2` you will see messages like

```
2023-10-30 14:04:44.800 -03 [19633] LOG C-0x55f164155320: (nodb)/(nouser)@unix(19635):6432 registered new auto-database: db=xpto
2023-10-30 14:04:44.800 -03 [19633] DEBUG C-0x55f164155320: xpto/(nouser)@unix(19635):6432 pause_client
2023-10-30 14:04:44.801 -03 [19633] NOISE S-0x55f16415c550: xpto/postgres@(bad-af):0 unix socket: /tmp/.s.PGSQL.9916
2023-10-30 14:04:44.801 -03 [19633] DEBUG S-0x55f16415c550: xpto/postgres@unix:9916 launching new connection to server
2023-10-30 14:04:44.801 -03 [19633] DEBUG S-0x55f16415c550: xpto/postgres@unix:9916 S: connect ok
2023-10-30 14:04:44.801 -03 [19633] LOG S-0x55f16415c550: xpto/postgres@unix:9916 new connection to server
2023-10-30 14:04:44.801 -03 [19633] NOISE S-0x55f16415c550: xpto/postgres@unix:9916 P: startup
2023-10-30 14:04:44.801 -03 [19633] DEBUG pktbuf_dynamic(512): 0x55f1641635e0
2023-10-30 14:04:44.801 -03 [19633] NOISE resync(14): done=0, parse=0, recv=0
2023-10-30 14:04:44.801 -03 [19633] NOISE S-0x55f16415c550: xpto/postgres@unix:9916 read pkt='R', len=9
2023-10-30 14:04:44.801 -03 [19633] DEBUG S-0x55f16415c550: xpto/postgres@unix:9916 calling login_answer
2023-10-30 14:04:44.801 -03 [19633] DEBUG S-0x55f16415c550: xpto/postgres@unix:9916 S: auth ok
2023-10-30 14:04:44.801 -03 [19633] NOISE S-0x55f16415c550: xpto/postgres@unix:9916 read pkt='E', len=101
2023-10-30 14:04:44.801 -03 [19633] WARNING server login failed: FATAL role "postgres" does not exist
2023-10-30 14:04:44.801 -03 [19633] NOISE kill_pool_logins_server_error: sqlstate: 28000
2023-10-30 14:04:44.801 -03 [19633] LOG S-0x55f16415c550: xpto/postgres@unix:9916 closing because: login failed (age=0s)
2023-10-30 14:04:44.801 -03 [19633] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
2023-10-30 14:04:45.109 -03 [19633] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
2023-10-30 14:04:45.445 -03 [19633] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
2023-10-30 14:04:45.775 -03 [19633] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
2023-10-30 14:04:46.110 -03 [19633] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 13 s
```

and it will try again and again. Since the `query_wait_timeout` is disabled (0), it keeps trying forever. The problem is that you misunderstood the authentication setup. The `auth_file` should include the `auth_user`. Hence, PgBouncer can connect to Postgres using the credentials from `auth_file`, execute the `auth_query` and proceed with the user authentication.

Maybe we should provide a hint saying that `auth_file` is missing. It would help users to solve issues like this one.

**Comment by panaxtri** [comment] 2023-10-30 17:56
I just didn't provide the entire settings file, here's the complete one

**/etc/pgbouncer/pgbouncer.ini**
```
[databases]
* = host=127.0.0.1 port=5432

[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /run/pgbouncer/pgbouncer.pid
listen_addr = *
listen_port = 6432
unix_socket_dir = /var/run/postgresql
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt
auth_user = ttt
auth_query = SELECT uname, phash FROM user_lookup(\$1)
admin_users = ttt
stats_users = ttt
ignore_startup_parameters = extra_float_digits,geqo,search_path,replication

max_client_conn = 7000
pool_mode = session
server_reset_query = DISCARD ALL
default_pool_size = 200
min_pool_size = 5
query_wait_timeout = 0
#query_wait_timeout = 100 

reserve_pool_size = 5
reserve_pool_timeout = 1

pkt_buf = 8192
listen_backlog = 4096

server_check_query = select 1
server_check_delay = 10

server_idle_timeout=3600

log_connections = 0
log_disconnections = 0
log_pooler_errors = 1
# verbose=2
```

**Comment by panaxtri** [comment] 2023-10-30 18:19
It seems to be a real bug
Upgraded to PgBouncer 1.20.0, same thing.
 pgbouncer -V
PgBouncer 1.20.0
libevent 2.1.8-stable

```
2023-10-30 21:16:50.774 MSK [6202] DEBUG launch_new_connection: already progress
2023-10-30 21:16:50.778 MSK [6202] NOISE resync(12): done=0, parse=0, recv=0
2023-10-30 21:16:50.778 MSK [6202] NOISE resync(12): done=1, parse=1, recv=1
2023-10-30 21:16:50.778 MSK [6202] DEBUG launch_new_connection: already progress
2023-10-30 21:16:50.781 MSK [6202] NOISE resync(12): done=0, parse=0, recv=0
2023-10-30 21:16:50.781 MSK [6202] NOISE S-0xe09b50: test777777/ttt@127.0.0.1:5432 read pkt='R', len=24
2023-10-30 21:16:50.781 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 calling login_answer
2023-10-30 21:16:50.781 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 S: req SASL
2023-10-30 21:16:50.781 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 S: SASL advertised mechanism: SCRAM-SHA-256
2023-10-30 21:16:50.781 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 SCRAM client-first-message = "n,,n=,r=......"
2023-10-30 21:16:50.781 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 P: send SASLInitialResponse
2023-10-30 21:16:50.781 MSK [6202] NOISE resync(12): done=24, parse=24, recv=24
2023-10-30 21:16:50.781 MSK [6202] DEBUG launch_new_connection: already progress
2023-10-30 21:16:50.782 MSK [6202] NOISE resync(12): done=0, parse=0, recv=0
2023-10-30 21:16:50.782 MSK [6202] NOISE S-0xe09b50: test777777/ttt@127.0.0.1:5432 read pkt='R', len=93
2023-10-30 21:16:50.782 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 calling login_answer
2023-10-30 21:16:50.782 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 S: SASL cont
2023-10-30 21:16:50.782 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 SCRAM server-first-message = "r=.....e,s=.....==,i=4096"
2023-10-30 21:16:50.801 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 SCRAM client-final-message = "c=biws,r=....="
2023-10-30 21:16:50.802 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 P: send SASLResponse
2023-10-30 21:16:50.802 MSK [6202] NOISE resync(12): done=93, parse=93, recv=93
2023-10-30 21:16:50.802 MSK [6202] DEBUG launch_new_connection: already progress
2023-10-30 21:16:50.805 MSK [6202] NOISE resync(12): done=0, parse=0, recv=0
2023-10-30 21:16:50.805 MSK [6202] NOISE S-0xe09b50: test777777/ttt@127.0.0.1:5432 read pkt='R', len=55
2023-10-30 21:16:50.805 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 calling login_answer
2023-10-30 21:16:50.805 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 S: SASL final
2023-10-30 21:16:50.805 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 SCRAM server-final-message = "v=......"
2023-10-30 21:16:50.805 MSK [6202] NOISE S-0xe09b50: test777777/ttt@127.0.0.1:5432 read pkt='R', len=9
2023-10-30 21:16:50.805 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 calling login_answer
2023-10-30 21:16:50.805 MSK [6202] DEBUG S-0xe09b50: test777777/ttt@127.0.0.1:5432 S: auth ok
2023-10-30 21:16:50.805 MSK [6202] NOISE S-0xe09b50: test777777/ttt@127.0.0.1:5432 read pkt='E', len=96
2023-10-30 21:16:50.805 MSK [6202] WARNING server login failed: FATAL database "test777777" does not exist
2023-10-30 21:16:50.806 MSK [6202] NOISE kill_ttt_logins_server_error: sqlstate: 3D000
2023-10-30 21:16:50.806 MSK [6202] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
2023-10-30 21:16:51.108 MSK [6202] DEBUG launching new connection to satisfy min_ttt_size
2023-10-30 21:16:51.108 MSK [6202] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
2023-10-30 21:16:51.108 MSK [6202] DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
2023-10-30 21:16:51.439 MSK [6202] DEBUG launching new connection to satisfy min_ttt_size
```

**Comment by panaxtri** [comment] 2023-10-30 19:22
**starce**
```
epoll_wait(4, [], 32, 329)              = 0
epoll_wait(4, [], 32, 1)                = 0
epoll_wait(4, [], 32, 1)                = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 17
fcntl(17, F_SETFD, FD_CLOEXEC)          = 0
fcntl(17, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(17, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
setsockopt(17, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(17, SOL_TCP, TCP_NODELAY, [1], 4) = 0
connect(17, {sa_family=AF_INET, sin_port=htons(5432), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(4, EPOLL_CTL_ADD, 17, {EPOLLOUT, {u32=17, u64=17}}) = 0
epoll_wait(4, [{EPOLLOUT, {u32=17, u64=17}}], 32, 322) = 1
epoll_ctl(4, EPOLL_CTL_DEL, 17, 0x7ffef4e16c0c) = 0
getsockopt(17, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
getsockname(17, {sa_family=AF_INET, sin_port=htons(41354), sin_addr=inet_addr("127.0.0.1")}, [28->16]) = 0
sendto(17, "\0\0\0\10\4\322\26/", 8, 0, NULL, 0) = 8
epoll_ctl(4, EPOLL_CTL_ADD, 17, {EPOLLIN, {u32=17, u64=17}}) = 0
epoll_wait(4, [{EPOLLIN, {u32=17, u64=17}}], 32, 318) = 1
recvfrom(17, "N", 8192, 0, NULL, NULL)  = 1
sendto(17, "\0\0\0*\0\3\0\0database\0test777777777\0u"..., 42, 0, NULL, 0) = 42
epoll_wait(4, [{EPOLLIN, {u32=17, u64=17}}], 32, 314) = 1
recvfrom(17, "R\0\0\0\27\0\0\0\nSCRAM-SHA-256\0\0", 8192, 0, NULL, NULL) = 24
getpid()                                = 15624
sendto(17, "p\0\0\0006SCRAM-SHA-256\0\0\0\0 n,,n=,r=i"..., 55, 0, NULL, 0) = 55
epoll_wait(4, [{EPOLLIN, {u32=17, u64=17}}], 32, 306) = 1
recvfrom(17, "R\0\0\0\\\0\0\0\vr=...."..., 8192, 0, NULL, NULL) = 93
sendto(17, "p\0\0\0lc=biws,r=...."..., 109, 0, NULL, 0) = 109
epoll_wait(4, [{EPOLLIN, {u32=17, u64=17}}], 32, 290) = 1
recvfrom(17, "R\0\0\0006\0\0\0\fv=...."..., 8192, 0, NULL, NULL) = 163
getpid()                                = 15624
write(3, "2023-10-30 22:14:24.096 MSK [156"..., 111) = 111
sendto(17, "X\0\0\0\4", 5, 0, NULL, 0)  = 5
epoll_ctl(4, EPOLL_CTL_DEL, 17, 0x7ffef4e166cc) = 0
close(17)                               = 0
epoll_wait(4, [], 32, 282)              = 0
epoll_wait(4, [], 32, 327)              = 0
epoll_wait(4, [], 32, 333)              = 0
epoll_wait(4, [], 32, 330)              = 0
epoll_wait(4, [], 32, 327)              = 0
epoll_wait(4, [], 32, 333)              = 0
```

**Comment by panaxtri** [comment] 2023-10-30 19:23
**Looks like I'll have to build from source and debug gdb --pid .....**

**Comment by eulerto** [comment] 2023-10-30 22:13
I wouldn't call it a bug but PgBouncer could do better to avoid shooting yourself in the foot. What you showed it is another side effect from a authentication misunderstanding. In this case, PgBouncer is trying to open connections forever in order to satisfy `min_pool_size`.

If I were you I wouldn't use such an old PgBouncer version and instead use a recent one that includes support for `auth_dbname` parameter (it was included in 1.19). This parameter allows you to use only one database to do the authentication instead of using the same database you are opening a connection. Hence, most of the authentication setup mistakes (such as `auth_query` objects that is not available in a certain database, no pg_hba.conf for a certain user/database pair, etc) can be avoided.

**Comment by JelteF** [comment] 2023-10-30 22:41
Setting `query_wait_timeout` to 0 is definitely not recommend, exactly for reasons like this. We're actually considering changing the default to 10 seconds #957.

**Comment by JelteF** [comment] 2023-10-30 22:49
If you close the client that used the wrong database name, the error goes away right?

**Comment by panaxtri** [comment] 2023-10-31 09:10
No, it doesn't disappear!
That's the point, that's why I started this issue.

**Comment by JelteF** [comment] 2023-10-31 09:24
In all your output it still shows the client as being connected:
From your first message:
> ```
>  type |   user   | database  |  state  |      addr      | port  |   local_addr   | local_port |      connect_time       |      request_time       | wait | wait_us | close_needed |    ptr    | link | remote_pid | tls | application_name
> ------+----------+-----------+---------+----------------+-------+----------------+------------+-------------------------+-------------------------+------+---------+--------------+-----------+------+------------+-----+------------------
>  C    | (nouser) | fgh       | waiting | 192.172.23.182 | 37004 | 192.172.23.183 |       6432 | 2023-10-23 12:09:23 MSK | 2023-10-23 12:09:23 MSK |    0 |       0 |            0 | 0x1c6d950 |      |          0 |     | psql
>  C    | (nouser) | fgh456    | waiting | 192.172.23.182 | 37094 | 192.172.23.183 |       6432 | 2023-10-23 12:10:07 MSK | 2023-10-23 12:10:07 MSK |    0 |       0 |            0 | 0x1c6de10 |      |          0 |     | psql
> ```

From your message with pgbouncer 1.20.0
> ```
>  C    | (nouser) | test777777 | waiting | 192.172.23.181 | 41548 | 192.172.23.183 |       6432 | 2023-10-30 21:36:25 MSK | 2023-10-30 21:36:25 MSK |    0 |       0 |            0 | 0x149c6b0 |      |          0 |     | psql
> ```

That's why I'm asking if disconnecting the client resolves the issue. `min_pool_size` will continue to try and ensure the minimum pool size when a client for that pool is still connected. Because query_wait_timeout is 0, pgbouncer will not cause the disconnection to happen. You need the client to actually close the connection. If you did that and there's still a client listed with `show clients` then that seems like a bug.

P.S. Maybe try not "yelling" so much when writing. It makes me much less likely to continue helping.

**Comment by panaxtri** [comment] 2023-10-31 09:28
In a dispute, the truth is born
Thank you for your help

**Comment by panaxtri** [comment] 2023-10-31 09:31
Client 
```
C | test777 | test777 | active | 192.172.23.181 | 41550 | 192.172.23.183 | 6432 | 2023-10-30 21:39:24 MSK | 2023-10-30 21:42:56 MSK | 0 | 0 | 0 | 0 | 0x149cb30 | 0x14a4290 | 0 | | | psql
```
connects with correct data and disconnects without any problems


"Problems" with this one, which entered the base name incorrectly
```
C | (nouser) | test77777777 | waiting | 192.172.23.181 | 41548 | 192.172.23.183 | 6432 | 2023-10-30 21:36:25 MSK | 2023-10-30 21:36:25 MSK | 0 | 0 | 0 | 0 | 0x149c6b0 | | | 0 | | | psql
```

**Comment by eulerto** [comment] 2023-11-30 01:49
@panaxtri It is not clear if you solve this problem. If so, close this issue.

**Closed as completed** 2024-02-20 13:35 UTC
Labels: support
