### ISSUE TITLE
Logs spammed with FIXME: query end, but query_start == 0 with npgsql

### ISSUE THREAD

**Issue by dezconnect** [pgbouncer/pgbouncer#376] opened 2019-03-22 13:59 UTC
Faced with that problem.

Solution from https://github.com/pgbouncer/pgbouncer/issues/277 not works.

I tried to use No Reset On Close=True in application but it is not solved that trouble.

**Comment by DavidPavlicek** [comment] 2019-03-27 14:16
In our case, this is caused by the command timeout on npgsql connection. Each time npgsql terminates command due to timeout, this appears in our log. So... try to avoid command timeouts on a client side.

**Comment by dezconnect** [comment] 2019-03-27 14:36
> In our case, this is caused by the command timeout on npgsql connection. Each time npgsql terminates command due to timeout, this appears in our log. So... try to avoid command timeouts on a client side.

Thanks, but it is not works for our case...

**Comment by dezconnect** [comment] 2019-03-29 14:53
Solved that problem via change log level for this warning and rebuild package for local repo.

**Comment by kleptog** [comment] 2019-04-19 13:34
This is possibly fixed by #253.

**Comment by dezconnect** [comment] 2019-04-20 11:44
> This is possibly fixed by #253.

No, I used last version of pgbouncer with that fix, but I faced with warnings. 
How I understood this linked with processing of non-blocking connections.

**Comment by fedordikarev** [comment] 2019-06-03 09:23
Hi everyone! Are there any updates on this issue?
We also use pgbouncer with npgsql and have this errors. We reproduce them on our QA environment (rate is several errors per second). So we could easily get any debug log or trace if needed. Just tell me which log level to use or what debug information could help you to investigate real root of this issue? (sorry, we don't have developers with enough knowledge of pgbouncer in our team, so we can't debug this issue by ourselves)

**Comment by dezconnect** [comment] 2019-06-04 02:36
You can find lines of code with these warnings and fix it to debug level. After that, you need to rebuild the package and use it.

**Comment by kpakozz96pyc** [comment] 2019-07-24 07:38
Also get the same error in pgbouncer-1.9.0-win32

**Comment by svb007** [comment] 2019-08-08 03:10
So have you tried the patch I put at the top of https://github.com/pgbouncer/pgbouncer/issues/277 ? that does at least get rid of the messages. I agree, https://github.com/pgbouncer/pgbouncer/pull/253 does not seem to fix this issue, but does seem to make npgsql pools behave better when connecting to pgbouncer

**Comment by dezconnect** [comment] 2019-08-08 12:37
> So have you tried the patch I put at the top of #277 ? that does at least get rid of the messages. I agree, #253 does not seem to fix this issue, but does seem to make npgsql pools behave better when connecting to pgbouncer

Yep, I compiled it with debug log level and it fixed this problem.

**Comment by bagafoot** [comment] 2020-01-13 08:18
@dezconnect I encounter the same issue but I don't know how to rebuild/compile package, can you show step by step how to do it ?

**Comment by roji** [comment] 2020-03-14 21:45
Seems to be a dup of #277

**Closed** 2021-07-13 09:48 UTC
