### ISSUE TITLE
Scheduling of server connections not equally distributed between waiting pools

### ISSUE THREAD

**Issue by jens-adeptable** [pgbouncer/pgbouncer#131] opened 2016-05-04 03:41 UTC
It appears as if pgbouncer does not schedule "fairly" between waiting pools of connections. I'm using transaction pooling. 

While performing load testing, I configured `max_db_connections` to 10 server connections. I have 3 different database users (named "A", "B", "C"). For each of them, I'm making 15 concurrent client connections to send queries. In total, each of the 3 users will send 5000 queries. My expectation would be that under this load scenario, I should see a similar distribution of how long queries take for each of the 3 users. But I can observe that queries for user "A" will be served with significantly better times. It seems like whenever a transaction has finished, pgbouncer gives the available connection to user "A", not to "B" or "C". In effect, I see lots of query timeouts (30s) for user "C".

In order to trouble shoot this, I also tested scenarios where user "C" already made 1000 out of 5000 queries, then activated user "B" (so both are now sending queries), then activated user "A" last when "C" made 2000 out of 5000 queries. But even in that scenario, user "A" quickly catches up and actually finishes all of its request before "B" and "C"

Peeking through the source code, I wonder if this is caused by the event loop iterating through all pools in alphabetical order, assigning available server sockets  first to user "A", starving "B" and "C".

**Comment by PJMODOS** [comment] 2016-05-31 10:07
If I understand correctly, this is expected behaviour:
**max_db_connections**
Do not allow more than this many connections per-database (regardless of pool - i.e. user). It should be noted that when you hit the limit, closing a client connection to one pool will not immediately allow a server connection to be established for another pool, because the server connection for the first pool is still open. Once the server connection closes (due to idle timeout), a new server connection will immediately be opened for the waiting pool

**Closed** 2016-05-31 10:11 UTC

**Comment by jens-adeptable** [comment] 2016-06-06 20:23
@PJMODOS thanks for responding. Yes, the behavior you quote in the documentation is expected. What is unexpected is is that in the moment of closing the connection, pgbouncer seems to always pick the same database user (i.e. the first one alphabetical order). I would have expected that some kind of round-robin scheduling is happening so that not one user can starve the other waiting users, which seems to be happening right now. Is this a know limitation?
