### ISSUE TITLE
Graceful backend RDS cluster migration is not hapenning 

### ISSUE THREAD

**Issue by sravankurra** [pgbouncer/pgbouncer#432] opened 2019-11-07 15:32 UTC
In my environment we are using PgBouncer (version: PgBouncer-1.9.0 and using the session pooling mode) in between the service and PostgreSQL Cluster. We installed PgBouncer on EC2 machines and attached those instances to NLB (network load balancer). When we are migrating back end RDS cluster, we are changing instance names in PgBouncer databases and doing online restart of PgBouncer using (-R) option. 

### Example 
  Database names in PgBouncer
```
gl_stg_write = host=old-cluster-master port=5432 dbname=sample
gl_stg_read_w = host=old-cluster-replica  port=5432 dbname=sample
```
While migrating to new cluster 
```
gl_stg_write = host=new-cluster-master port=5432 dbname=sample
gl_stg_read_w = host=new-cluster-replica  port=5432 dbname=sample
```

### Problems
We are doing online restart of PgBouncer using **/usr/local/bin/pgbouncer -d -R -u pgbouncer /xxx/service/pgbouncer/pgbouncer.ini**
1. Some connections are not dropping like whichever the connections showing active in show servers they are not dropping (no transaction is happening from client side and in RDS level That active PID from PgBouncer servers is in idle state)
2. After some time if the client is running any transaction with that active connection the transaction is going to old RDS cluster
3. If we restart the client to drop all active connections from the client side and try to reconnect again some connections are connected to old RDS cluster only (our client is in Kubernetes so in fraction of sections only connections will come Up)

### Tested with some parameters change 

We enabled two parameters  thought like they are going to helpful 
```
 server_fast_close value to 1
dns_max_ttl value  to 0

```
These parameters also not helped in our use case.

Some one please suggest me like
1. Is there any way to migrate gracefully back end RDS cluster with same DB names in PGBouncer?
2. Any other parameters can help with my use case?

**Comment by sravankurra** [comment] 2019-11-08 14:51
any thoughts on this ^^ folks

**Comment by petere** [comment] 2019-11-10 06:53
Are you using TLS connections? Online restart doesn't work for those.

**Comment by sravankurra** [comment] 2019-11-11 15:34
Hey @petere 
Thank you for your response. We are using TCP Forward in NLB.

**Comment by sdemontfort** [comment] 2019-12-16 21:49
I managed to solve the RDS AZ failover issue for our team and we’re using this change in production:
https://github.com/pgbouncer/pgbouncer/pull/428

It solves the issue of TCP connections being stuck open to the old RDS instance (pre-AZ failover).

**Comment by sravankurra** [comment] 2020-01-07 14:49
Hi @sdemontfort Thank you for your response, We solved the issue enabling a server_fast_close. When we enable server_fast_close and running reload it quickly changing the connections from old cluster to new.

**Comment by petere** [comment] 2020-01-10 08:52
It appears this was a usage error/misunderstanding, not a bug, so closing.

**Closed by petere** 2020-01-10 08:52 UTC
