### ISSUE TITLE
can't connect to pgbouncer via jdbc. unknown pkt from client: 90

### ISSUE THREAD

**Issue by vaibhavarora** [pgbouncer/pgbouncer#1065] opened 2024-05-07 22:58 UTC
I can connect to pgbouncer from psql and query database via that 

but when connecting from the app via the JDBC, get back errors

"unknown pkt from client: 90/0x5a"

PgBouncer 1.22.1

**Comment by JelteF** [comment] 2024-05-08 06:25
Could you share how you are connecting to PgBouncer with JDBC? And which JDBC version are you using? Also did this work before and did it break after some change, or is it the first time you are trying it?

**Comment by JelteF** [comment] 2024-05-08 09:03
can you share your pgbouncer config file? And can you share logs of pgbouncer when running in very verbose mode (start it with `-vvv` or add `verbose = 3` to the `[pgbouncer]` section of the config)

**Comment by JelteF** [comment] 2024-05-08 15:31
Also double checking the dbname you use is not `pgbouncer` right? Because that is the admin database.

**Comment by eulerto** [comment] 2024-05-08 15:59
What's the JDBC version? Is it a specific transaction that causes it? If so, could you share it?

**Comment by vaibhavarora** [comment] 2024-05-08 17:55
ini file

 [databases]
 postgres = host=localhost port=5432 dbname=postgres

 [pgbouncer]
 listen_port = 6432
 listen_addr = localhost
 auth_type = trust
 auth_file = userlist.txt
 logfile = pgbouncer.log
 pidfile = pgbouncer.pid
 admin_users = xxx
 ignore_startup_parameters = extra_float_digits, application_version, application_name

**Comment by vaibhavarora** [comment] 2024-05-08 17:56
"Also double checking the dbname you use is not pgbouncer right?"

No, it's not

**Comment by eulerto** [comment] 2024-08-19 02:06
There isn't enough information to say if it is a bug or not. Having said that, I'm closing this issue because we couldn't reproduce it and the reporter also didn't provide a test case.

**Closed by eulerto** 2024-08-19 02:06 UTC
Labels: moreinfo, pending-close
