### ISSUE TITLE
Error: "prepared statement "pdo_stmt_00000001" does not exist" - transaction mode with PHP 8.3.9

### ISSUE THREAD

**Issue by VinnyVicious** [pgbouncer/pgbouncer#1129] opened 2024-08-01 21:23 UTC
I have a very simple PHP application running with PDO, connecting to pgbouncer with the following configuration:

```
[databases]
core = connection_details

[pgbouncer]
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 20
syslog = 1
application_name_add_host = 1
listen_port = 6432
listen_addr = localhost
auth_type = any
pidfile = /etc/pgbouncer/pgbouncer.pid
```

And versions:

```
PgBouncer 1.23.0
libevent 2.1.12-stable
adns: evdns2
tls: OpenSSL 3.0.2 15 Mar 2022
systemd: yes
```

Example connection in PHP:

```
$db = new PDO(getenv('DATABASE_DSN'), null, null, [
    PDO::ATTR_PERSISTENT => false,
]);
```

From time to time, I get the following error:

```
Invalid sql statement name: 7 ERROR:  prepared statement "pdo_stmt_00000001" does not exist
```

pgbouncer is installed on the same machine as the multiple running php-fpm instances.

**Comment by JelteF** [comment] 2024-08-01 21:57
You should disable prepared statements with PHP its PDO: https://www.pgbouncer.org/faq.html#how-to-use-prepared-statements-with-transaction-pooling

This is needed until PDO addresess this issue: https://github.com/php/php-src/issues/12940

Duplicate of: https://github.com/pgbouncer/pgbouncer/issues/991

**Closed by JelteF** 2024-08-01 21:57 UTC

**Comment by VinnyVicious** [comment] 2024-08-01 22:03
I got this to work by adding the following on pgbouncer.ini:

```
max_prepared_statements = 1000
```

**Comment by JelteF** [comment] 2024-08-01 22:07
Unless https://github.com/php/php-src/issues/12940 is addressed you'll probably still run into such errors, just fewer of them.

You can disable prepared statements in PDO using this snipped until that happens.
```
$db = new PDO("dsn", "user", "pass", array(PDO::ATTR_EMULATE_PREPARES => true));
```
