### ISSUE TITLE
FATAL @src/objects.c:420 in function put_in_order(): put_in_order: found existing elem

### ISSUE THREAD

**Issue by tpo** [pgbouncer/pgbouncer#1103] opened 2024-07-04 17:39 UTC
Looks identical to issue #968

Today I've upgraded pgbouncer from 1.22.1-1.pgdg22.04+1 to 1.23.0-1.pgdg22.04+1 via `apt`.

1.5h after the upgrade I had this in the logs:

    [...] FATAL @src/objects.c:420 in function put_in_order(): put_in_order: found existing elem

 and pgbouncer died.

**Comment by eulerto** [comment] 2024-07-04 18:25
It is hard to say without your configuration file and the connection string.

**Comment by tpo** [comment] 2024-07-04 20:45
> It is hard to say without your configuration file and the connection string

But there isn't a configuration that should kill pgbouncer after it's been running and proxying connections, correct?

**Comment by eulerto** [comment] 2024-07-04 21:15
@tpo This message indicates a bug.

Follow these instructions to install an old PgBouncer version:

```
sudo apt install curl ca-certificates
sudo install -d /usr/share/postgresql-common/pgdg
sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt-archive.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt update
sudo apt list -a pgbouncer
sudo apt install pgbouncer=1.19.1-1.pgdg22.04+1
```

You should obtain a list of old packages such as:

```
$ sudo apt list -a pgbouncer
Listing... Done
pgbouncer/jammy-pgdg-archive 1.22.1-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.22.0-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.21.0-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.20.1-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.20.0-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.19.1-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.19.0-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.18.0-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.17.0-4.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.17.0-3.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.17.0-1.pgdg22.04+1 amd64
pgbouncer/jammy-pgdg-archive 1.16.1-1.pgdg20.04+1 amd64
pgbouncer/jammy 1.16.1-1ubuntu1 amd64
```

**Comment by tpo** [comment] 2024-07-04 22:08
@eulerto - many, many thanks!!!

It seems that the archive is broken:

```
# apt-get update
[...]
Err:6 https://apt-archive.postgresql.org/pub/repos/apt focal-pgdg InRelease                                                                 
  403  Forbidden [IP: 2600:9000:2761:4600:b:5965:3380:93a1 443]
[...]
E: Failed to fetch https://apt-archive.postgresql.org/pub/repos/apt/dists/focal-pgdg/InRelease  403  Forbidden [IP: 2600:9000:2761:4600:b:5965:3380:93a1 443]
E: The repository 'https://apt-archive.postgresql.org/pub/repos/apt focal-pgdg InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

It's not good that the repo is broken, however, in the meantime, while you sent me the instructions, I have rebuild the old 1.22.1-1.pgdg22.04+1 version from sources. And fortunately it works.

I'll go catch some sleep and come back tomorrow.

In theory I can send you my config however I'm a bit reluctant: security through obscurity...

Anyway, let me know if there's something particular I can do to fix the v1.23 problem.

Again: thanks a lot @eulerto !!!!

**Comment by JelteF** [comment] 2024-07-05 09:52
> In theory I can send you my config however I'm a bit reluctant: security through obscurity...

That would definitely be helpful. To be able to see if the reason is the same as the one reported in https://github.com/pgbouncer/pgbouncer/issues/968 and https://github.com/pgbouncer/pgbouncer/issues/314

Feel free to anomimyze any specifics like IP addresses and user names.

> Anyway, let me know if there's something particular I can do to fix the v1.23 problem.

I guess the workaround is change your config in a way that doesn't exhibit the problem. If you want to actually fix it, a PR is definitely appreciated.

**Comment by tpo** [comment] 2024-07-05 15:44
Here you go:

```
[databases] 
XXXXX = dbname=empty host=localhost user=uempty password=YYYYY
[... long list of similar entries ...]

YYYYY = host=db.host.example.org auth_user=pgbouncer
[... long list of similar entries ...]

* = host=db.host.example.org auth_user=pgbouncer

[users]

[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = 1.2.3.4
listen_port = 5432
unix_socket_dir = /var/run/pgbouncer
client_tls_sslmode = allow
client_tls_ca_file   = /etc/ssl/certs/ca.cert.pem
client_tls_key_file  = /etc/ssl/privkey.pem
client_tls_cert_file = /etc/ssl/fullchain.pem
client_tls_protocols = all
server_tls_sslmode = prefer
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_query = SELECT uname, phash FROM user_lookup($1)
admin_users = postgres, pgbouncer
stats_users = postgres, pgbouncer
pool_mode = transaction
ignore_startup_parameters = extra_float_digits
max_client_conn = 440
reserve_pool_size = 50 
reserve_pool_timeout = 3
server_idle_timeout = 60
client_idle_timeout = 600
client_login_timeout = 20
```

As you'll note IPs, host names and some user names have been changed.

**Comment by tpo** [comment] 2024-07-05 17:13
@eulerto , in your instructions above:

> ```
> [...]
> sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt-archive.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
> [...]
> ```

That should be `https://apt-archive.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg-archive` instead. That's why my `apt update` above failed :grimacing: 

In case you copy/pasted those instructions from somewhere, then that source should probably be fixed :grimacing: (thank you in any case!!!)

**Comment by dmitry-lipetsk** [comment] 2024-07-05 19:57
Hello,

I have not an enough experience with pgbouncer, so my idea about this issue may be incorrect :)

I think, a problem in get_pool+new_pool functions and two different credentials object with one name.

To say more exactly, a problem in put_in_order ocurres when this code
https://github.com/pgbouncer/pgbouncer/blob/bc6bf4fdd0777f283fa9357e999765abf0f2f587/src/objects.c#L370
returns zero value.

I see two points where sequential calls of get_pool may create a problem in put_in_order.

**-- First point**
start_auth_query function calls get_pool with client->db->auth_user_credentials object.

client->db->auth_user_credentials assigned with find_global_credentials/add_global_credentials (these functions works with global user_tree).

So client->db->auth_user_credentials points to element of global user_tree;

**-- Second point**
do_full_maint has the following code:

```c
statlist_for_each_safe(item, &database_list, tmp) {
	db = container_of(item, PgDatabase, head);
	if (database_min_pool_size(db) > 0 && db->forced_user_credentials != NULL) {
		get_pool(db, db->forced_user_credentials);
	}
}
```
it calls get_pool with db->forced_user_credentials.

db->forced_user_credentials is assigned in force_user_credentials and:
1. is always unique (is not listed in global user_tree).
2. has equal (by name) element in user_tree 

--
May be do_full_maint is called (with empty db->forced_user_credentials->pool_list) immediately after a call of start_auth_query and it tries to create a problem pool?

**Comment by eulerto** [comment] 2024-07-06 03:57
> @eulerto , in your instructions above:
> 
> > ```
> > [...]
> > sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt-archive.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
> > [...]
> > ```
> 
> That should be `https://apt-archive.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg-archive` instead. That's why my `apt update` above failed 😬
> 
> In case you copy/pasted those instructions from somewhere, then that source should probably be fixed 😬 (thank you in any case!!!)

It was a typo. Instructions are available at

https://apt-archive.postgresql.org/

I updated the previous comment just in case someone uses it.

**Comment by dmitry-lipetsk** [comment] 2024-07-06 09:04
Hello

I was able to reproduce this problem.

I used my idea, that I described above.

It is a really simple to do.

**pgbouncer.ini file**

```
[databases]

* = host=localhost user=postgres min_pool_size=2

[pgbouncer]

listen_port = 6432

listen_addr = *

auth_type = md5
auth_file = /usr/local/bin/userlist.txt
auth_query = SELECT usename, passwd FROM pg_shadow where usename = $1
auth_dbname = test
auth_user = postgres

logfile = /home/dima/pgbouncer.log

pidfile = /home/dima/pgbouncer.pid

admin_users = postgres

```
**userlist.txt file**:

`"postgres" "pg"
`

Just execute in a terminal the following query:

`psql -h localhost -p 6432 -d db2 -U virt2
`

**Stack**
```
put_in_order(struct List * newitem, struct StatList * list, int (*)(struct List *, struct List *) cmpfn) (/home/dima/.MY/GitHUB2/pgbouncer/work2/src/objects.c:420)
new_pool(PgDatabase * db, PgCredentials * user_credentials) (/home/dima/.MY/GitHUB2/pgbouncer/work2/src/objects.c:717)
get_pool(PgDatabase * db, PgCredentials * user_credentials) (/home/dima/.MY/GitHUB2/pgbouncer/work2/src/objects.c:769)
do_full_maint(int sock, short flags, void * arg) (/home/dima/.MY/GitHUB2/pgbouncer/work2/src/janitor.c:719)
libevent-2.1.so.7![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libevent-2.1.so.7!event_base_loop (Unknown Source:0)
main_loop_once() (/home/dima/.MY/GitHUB2/pgbouncer/work2/src/main.c:821)
main(int argc, char ** argv) (/home/dima/.MY/GitHUB2/pgbouncer/work2/src/main.c:1109)
```

I hope it will help you.

**Comment by dmitry-lipetsk** [comment] 2024-07-06 22:17
Hello,

I can offer the following "hack" fix for this problem.

```c
/* compare pool names, for use with put_in_order */
static int cmp_pool(struct List *i1, struct List *i2)
{
	PgPool *p1 = container_of(i1, PgPool, head);
	PgPool *p2 = container_of(i2, PgPool, head);
	if (p1->db != p2->db) {
		const int c1 = strcmp(p1->db->name, p2->db->name);
		Assert(c1 != 0);
		return c1;
	}
	if (p1->user_credentials != p2->user_credentials) {
		if (p1->user_credentials == NULL) {
			return 1;
		}
		if (p2->user_credentials == NULL) {
			return -1;
		}
		{
			const int c2 = strcmp(p1->user_credentials->name, p2->user_credentials->name);
			if (c2)
				return c2;

			/* Life is hard */
			/* Assert(false); */

			if (p1->user_credentials < p2->user_credentials)
				return -1;

			return 1;
		}
	}
	return 0;
}
```
Built-in tests said OK.

This test works, too:
```
> psql -h localhost -p 6432 -d db2 -U virt2
psql: error: connection to server at "localhost" (127.0.0.1), port 6432 failed: FATAL:  no such user
```

DO NOT USE IT IN PRODUCTION CODE, PLEASE!

**Comment by dmitry-lipetsk** [comment] 2024-07-07 10:20
Hello,

I think, I understand the reason of this problem - PgCredentials::pool_list is useless and incorrect.

get_pool must work with global pool_list and must check Credentials names (not pointers). The second thing is important because we can have multiple Credentials with one name.

So

1. Update get_pool with:
``` c
PgPool *get_pool(PgDatabase *db, PgCredentials *user_credentials)
{
	struct List *item;
	PgPool *pool;

	if (!db || !user_credentials)
		return NULL;

	Assert(user_credentials->name[0]);

	list_for_each(item, &pool_list.head) {
		pool = container_of(item, PgPool, head);
		Assert(pool->db);
		Assert(pool->user_credentials);
		Assert(pool->user_credentials->name[0]);
		if (pool->db != db)
			continue;
		if (strcmp(pool->user_credentials->name, user_credentials->name) != 0)
			continue;
		return pool;
	}

	return new_pool(db, user_credentials);
}
```

2. Update cmp_pool with:
``` c
static int cmp_pool(struct List *i1, struct List *i2)
{
	PgPool *p1 = container_of(i1, PgPool, head);
	PgPool *p2 = container_of(i2, PgPool, head);

	Assert(p1->db);
	Assert(p2->db);
	Assert(p1->user_credentials);
	Assert(p2->user_credentials);

	if (p1->db != p2->db) {
		const int c1 = strcmp(p1->db->name, p2->db->name);
		Assert(c1 != 0);
		return c1;
	}

	{
		const int c2 = strcmp(p1->user_credentials->name, p2->user_credentials->name);
		if (c2)
			return c2;
	}

	return 0;
}
```

3. Delete PgCredentials::pool_list and all the references on it.

Built-in tests and another things are ok. May be, built-in tests do not catch a potential mistake in my this fix.

I don't touch the question of optimization because at the current time it is not important.

Any comments?

Thanks.

**Comment by AndrewJackson2020** [comment] 2024-07-08 21:46
> Here you go:
> 
> ```
> [databases] 
> XXXXX = dbname=empty host=localhost user=uempty password=YYYYY
> [... long list of similar entries ...]
> 
> YYYYY = host=db.host.example.org auth_user=pgbouncer
> [... long list of similar entries ...]
> 
> * = host=db.host.example.org auth_user=pgbouncer
> 
> [users]
> 
> [pgbouncer]
> logfile = /var/log/postgresql/pgbouncer.log
> pidfile = /var/run/postgresql/pgbouncer.pid
> listen_addr = 1.2.3.4
> listen_port = 5432
> unix_socket_dir = /var/run/pgbouncer
> client_tls_sslmode = allow
> client_tls_ca_file   = /etc/ssl/certs/ca.cert.pem
> client_tls_key_file  = /etc/ssl/privkey.pem
> client_tls_cert_file = /etc/ssl/fullchain.pem
> client_tls_protocols = all
> server_tls_sslmode = prefer
> auth_type = md5
> auth_file = /etc/pgbouncer/userlist.txt
> auth_query = SELECT uname, phash FROM user_lookup($1)
> admin_users = postgres, pgbouncer
> stats_users = postgres, pgbouncer
> pool_mode = transaction
> ignore_startup_parameters = extra_float_digits
> max_client_conn = 440
> reserve_pool_size = 50 
> reserve_pool_timeout = 3
> server_idle_timeout = 60
> client_idle_timeout = 600
> client_login_timeout = 20
> ```
> 
> As you'll note IPs, host names and some user names have been changed.

Do you have your user list.txt and the connection string that causes the crash? Would like to recreate but hard to do especially not knowing the connection string.

**Comment by tpo** [comment] 2024-07-09 06:09
> @tpo Do you have your user list.txt and the connection string that causes the crash? Would like to recreate but hard to do especially not knowing the connection string.

https://github.com/pgbouncer/pgbouncer/issues/1103#issuecomment-2211713650 ?

**Comment by ruimarinho** [comment] 2024-07-10 15:18
I encountered a similar issue while upgrading to version 1.23. I only have three entries on my userlist.txt for `stats_users` basically, one of them being in plaintext as illustrated by @dmitry-lipetsk. Using `auth_query` for remaining database lookups.

Considering these problems, it might be worth recalling version 1.23.0?

**Comment by depesz** [comment] 2024-07-16 07:16
Hi. 1.23 killed my pgbouncer twice within 6 hour window, and I don't even have that much traffic on this server.

I'd say that 1.23 should be recalled and/or fix should be there.

The problem, in both cases, was:

```
Jul 16 03:48:30 lana pgbouncer[1212860]: stats: 0 xacts/s, 0 queries/s, 0 client parses/s, 0 server parses/s, 0 binds/s, in 80352 B/s, out 80401 B/s, xact 18833 us, query 18833 us, wait 215 us
Jul 16 03:49:30 lana pgbouncer[1212860]: stats: 0 xacts/s, 0 queries/s, 0 client parses/s, 0 server parses/s, 0 binds/s, in 80680 B/s, out 80899 B/s, xact 16868 us, query 16868 us, wait 6 us
Jul 16 03:49:37 lana pgbouncer[1212860]: @src/objects.c:420 in function put_in_order(): put_in_order: found existing elem
```

As in: all works well, then I get the put_in_order error, and pgbouncer dies.

**Comment by JelteF** [comment] 2024-07-22 08:01
A fix for this issue is here, which we plan to release this week: https://github.com/pgbouncer/pgbouncer/pull/1120

In the mean time as a workaround, it should work to put your `auth_user` in the `auth_file`.

**Comment by depesz** [comment] 2024-07-22 11:29
It might help, but in my case, auth_user was in auth_file:

relevant parts of config(s):

```
=# grep auth_user pgbouncer.ini
rtdb = host=127.0.0.1 port=5433 auth_user=pgbouncer pool_mode=session
roundcube = host=127.0.0.1 port=5433 auth_user=pgbouncer pool_mode=session
* = host=127.0.0.1 port=5433 auth_user=pgbouncer

=# grep auth_file pgbouncer.ini
auth_file = /etc/pgbouncer/userlist.txt

=# grep -c '"pgbouncer"' /etc/pgbouncer/userlist.txt
1
```

**Comment by JelteF** [comment] 2024-07-22 12:02
@depesz hmm that's different than the cases I've seen so far. Any chance you could try the PR to find out if that solves your issue too?

**Comment by depesz** [comment] 2024-07-22 12:52
Well, I rolled back to 1.18 (latest available in this debian). Upgrade makes me feel uneasy, as it's kinda-production box. So does using custom build there. And I don't really have test environment for this :(

**Comment by AndrewJackson2020** [comment] 2024-07-22 13:47
> Well, I rolled back to 1.18 (latest available in this debian). Upgrade makes me feel uneasy, as it's kinda-production box. So does using custom build there. And I don't really have test environment for this :(

Hi, I'm trying to replicate the issue that you are seeing. Do you know what connection string crashed your server?

**Comment by depesz** [comment] 2024-07-22 14:07
> @depesz can you share your full config (with private stuff commented out)? That would probably make it easier to reproduce.

Sure:

```
=# cat pgbouncer.ini
[databases]
rtdb = host=127.0.0.1 port=5433 auth_user=pgbouncer pool_mode=session
roundcube = host=127.0.0.1 port=5433 auth_user=pgbouncer pool_mode=session
* = host=127.0.0.1 port=5433 auth_user=pgbouncer

[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = 127.0.0.1
listen_port = 5432
unix_socket_dir = /var/run/postgresql

auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1

admin_users = pgbouncer, postgres, depesz
stats_users = pgbouncer, postgres, depesz

pool_mode = transaction

server_reset_query = DISCARD ALL

max_client_conn = 50
default_pool_size = 10
log_connections = 0
log_disconnections = 0
log_pooler_errors = 1
```

userlist.txt has only one account - pgbouncer.

**Comment by depesz** [comment] 2024-07-22 14:10
> Hi, I'm trying to replicate the issue that you are seeing. Do you know what connection string crashed your server?

There are multiple (~ 10) apps on this server, each with their own db. Logs, as far as I know didn't show which app caused this particular problem, and I don't really have a good way to check logs from all the apps (some of them don't have logs, or would just log "connecting to db failed").

**Comment by depesz** [comment] 2024-07-22 14:12
For whatever it's worth - each db/app has its own user, and they are usually named the same way, as in: user named xyz will connect to db xyz.

connections are always to 127.0.0.1 to port 5432

**Comment by ruimarinho** [comment] 2024-07-22 17:56
The setup I have is very similar to the one @depesz has and I also experienced the same bug, so I think there's more to it.

**Comment by jflambert** [comment] 2024-07-30 15:08
@AndrewJackson2020 we are able to replicate with a very simple docker-compose file, using pgbouncer v1.23.0 (credit to @Zoe2936)

```
services:
  db:
    container_name: mastodon-db
    image: postgres:15-alpine
    restart: always
    environment:
      - "TZ=Europe/Berlin"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=mastodon"
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
  pgbouncer:
    container_name: mastodon-pgbouncer
    image: edoburu/pgbouncer:latest
    restart: always
    depends_on:
      - db
    environment:
      - "TZ=Europe/Berlin"
      - "DB_HOST=db"
      - "AUTH_TYPE=trust"
      - "MAX_CLIENT_CONN=200"
      - "DEFAULT_POOL_SIZE=20"
      - "POOL_MODE=transaction"
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost']
```

**Comment by AndrewJackson2020** [comment] 2024-07-30 15:38
> @AndrewJackson2020 and @JelteF we are able to replicate with a very simple docker-compose file, using docker-pgbouncer v1.23.0 (credit to @Zoey2936), wasn't an issue with v1.22.1
> 
> ```
> services:
>   db:
>     container_name: mastodon-db
>     image: postgres:15-alpine
>     restart: always
>     environment:
>       - "TZ=Europe/Berlin"
>       - "POSTGRES_HOST_AUTH_METHOD=trust"
>       - "POSTGRES_DB=mastodon"
>     shm_size: 256mb
>     healthcheck:
>       test: ['CMD', 'pg_isready', '-U', 'postgres']
>   pgbouncer:
>     container_name: mastodon-pgbouncer
>     image: edoburu/pgbouncer:latest
>     restart: always
>     depends_on:
>       - db
>     environment:
>       - "TZ=Europe/Berlin"
>       - "DB_HOST=db"
>       - "AUTH_TYPE=trust"
>       - "MAX_CLIENT_CONN=200"
>       - "DEFAULT_POOL_SIZE=20"
>       - "POOL_MODE=transaction"
>     healthcheck:
>       test: ['CMD', 'pg_isready', '-h', 'localhost']
> ```

@jflambert Are you able to test this against the commit in #1120 to see if that fixes it? This PR is supposed to fix all of the known issues that trigger the put_in_order error and it would be helpful to know if this is not the case.

**Comment by jflambert** [comment] 2024-07-30 20:15
@AndrewJackson2020 tested! works great!!!

ETA on 1.23.1?

**Closed** 2024-08-01 17:34 UTC
Labels: bug

**Comment by jflambert** [comment] 2024-08-02 12:05
Awesome. Well, I'll be releasing `docker-pgbouncer:v1.23.1-p0` ASAP ;)
