### ISSUE TITLE
In Docker, pgbouncer does not resolve server hostname

### ISSUE THREAD

**Issue by mcd-php** [pgbouncer/pgbouncer#122] opened 2016-03-18 11:17 UTC
Then I configured docker-compose.yml in regular way and started my project, I got:

`14 WARNING lookup failed: postgres: result=-2`

Then I added the following to the start script, the entire project worked:

``` bash
POSTGRES_ORIG_HOST_IP=`host -t a ${POSTGRES_ORIG_HOST} | cut -d ' ' -f 4`

cat << EOF > /etc/pgbouncer/pgbconf.ini
[databases]
* = host=${POSTGRES_ORIG_HOST_IP} port=${POSTGRES_ORIG_PORT}
; ...
EOF
```

This clearly shows what Docker is not at blame - host is resolvable inside. It's pgbouncer who cannot resolve for some strange reason.

Versions:
docker -v: 1.10.3, build 20f81dd
docker-compose -v: 1.6.2, build unknown
pgbouncer -V: 1.7.2

**Comment by markokr** [comment] 2016-03-18 13:43
What DNS backend are you using?

**Comment by mcd-php** [comment] 2016-03-18 14:07
Have no idea, never had to configure, everything worked out of the box until now. 

My project now runs on one machine both in development and (pre-)production.

So probably `bridge` networking, since `overlay` takes configuring cluster with docker swarm and consul.

**Comment by markokr** [comment] 2016-03-18 14:11
I mean how pgbouncer was built - it can use different libs to resolve dns.  it printed that info when configuring, also it's in log:

LOG process up: pgbouncer 1.7.2, libevent 2.0.16-stable (epoll), adns: c-ares 1.11.0, tls: OpenSSL 1.0.1 14 Mar 2012

Please paste your log line for it.

**Comment by mcd-php** [comment] 2016-03-18 14:25
22 LOG process up: pgbouncer 1.7.2, libevent 2.0.21-stable (epoll), adns: evdns2, tls: OpenSSL 1.0.1k 8 Jan 2015

**Comment by markokr** [comment] 2016-03-18 14:30
So it's likely evdns does not work for you, please compile against c-ares, does that work?

**Comment by mcd-php** [comment] 2016-03-18 15:40
Failed.
Help about ./configure options is missing or insufficient ;(
```
./configure: line 6361: syntax error near unexpected token `CARES,'
./configure: line 6361: `  PKG_CHECK_MODULES(CARES, libcares >= 1.6.0, use_cares=yes, use_cares=no)'
```
```Dockerfile
FROM debian:jessie

## Based on:
## https://hub.docker.com/r/mbentley/ubuntu-pgbouncer/~/dockerfile/
## https://github.com/mbentley/dockerfiles/tree/master/ubuntu/pgbouncer

RUN apt-get update
RUN apt-get -y --no-install-recommends install automake
RUN apt-get -y --no-install-recommends install build-essential
RUN apt-get -y --no-install-recommends install ca-certificates
RUN apt-get -y --no-install-recommends install git 
RUN apt-get -y --no-install-recommends install libc-ares-dev
RUN apt-get -y --no-install-recommends install libev-libevent-dev
RUN apt-get -y --no-install-recommends install libev-dev
RUN apt-get -y --no-install-recommends install libevent-dev
RUN apt-get -y --no-install-recommends install libtool
RUN apt-get -y --no-install-recommends install wget

RUN mkdir -p /opt && cd /opt
WORKDIR /opt
RUN git clone https://github.com/pgbouncer/pgbouncer.git
WORKDIR /opt/pgbouncer
RUN git checkout pgbouncer_1_7_2
RUN git submodule init
RUN git submodule update
RUN ./autogen.sh
RUN ./configure --enable-evdns=no
RUN make
RUN make install

## Disregard below this, focus is on building

ENV PG_ENV_POSTGRESQL_MAX_CLIENT_CONN 10000
ENV PG_ENV_POSTGRESQL_DEFAULT_POOL_SIZE 50
ENV PG_ENV_POSTGRESQL_SERVER_IDLE_TIMEOUT 240

# ADD run.sh /usr/local/bin/run
RUN mkdir -p /usr/local/bin/ && wget https://github.com/mbentley/dockerfiles/blob/master/ubuntu/pgbouncer/run.sh -O /usr/local/bin/run

RUN chmod +x /usr/local/bin/run

EXPOSE 6432

CMD ["/usr/local/bin/run"]
```

**Comment by markokr** [comment] 2016-03-18 15:45
If you are building from git, you need pkg.m4 which comes from pkg-config package.

**Comment by mcd-php** [comment] 2016-03-21 09:01
This finally works:
```Dockerfile
FROM debian:jessie

## Based on:
## https://hub.docker.com/r/mbentley/ubuntu-pgbouncer/~/dockerfile/
## https://github.com/mbentley/dockerfiles/tree/master/ubuntu/pgbouncer

## Install build deps, build and cleanup in one shot
RUN apt-get update \
    && apt-get -y --no-install-recommends install \ 
        automake \
        build-essential \
        ca-certificates \
        git \
        libc-ares2 \
        libc-ares-dev \
        libev4 \
        libev-dev \
        libevent-2.0-5 \
        libevent-dev \
        libssl1.0.0 \
        libssl-dev \
        libtool \
        pkg-config \
        wget \
    && mkdir -p /opt && cd /opt \
    && git clone https://github.com/pgbouncer/pgbouncer.git \
    && cd /opt/pgbouncer \
    && git checkout pgbouncer_1_7_2 \
    && git submodule init \
    && git submodule update \
    && ./autogen.sh \
    && ./configure --enable-evdns=no \
    && make \
    && make install \
    && apt-get remove -y \
        automake \
        build-essential \
        ca-certificates \
        git \
        libc-ares-dev \
        libev-dev \
        libevent-dev \
        libssl-dev \
        libtool \
        pkg-config \
        wget \
    && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

## After `make install` pgbouncer needs some extra touches to make it work
RUN mkdir -p /etc/pgbouncer/
RUN mkdir -p /var/run/postgresql/
RUN groupadd --system postgres
RUN useradd -g postgres postgres
RUN touch /var/log/postgresql
RUN chown postgres:postgres /var/log/postgresql
RUN chown postgres:postgres /var/run/postgresql/

ENV PG_ENV_POSTGRESQL_MAX_CLIENT_CONN 10000
ENV PG_ENV_POSTGRESQL_DEFAULT_POOL_SIZE 50
ENV PG_ENV_POSTGRESQL_SERVER_IDLE_TIMEOUT 240

ADD run.sh /usr/local/bin/run
# RUN mkdir -p /usr/local/bin/ && wget https://github.com/mbentley/dockerfiles/raw/master/ubuntu/pgbouncer/run.sh -O /usr/local/bin/run
RUN chmod +x /usr/local/bin/run

EXPOSE 6432

CMD ["/usr/local/bin/run"]
```

Will you release .deb package capable to work in docker, or better yet, your image on docker hub ? 

P.S.
Trying to say `make deb`, errors:
E: pgbouncer changes: bad-distribution-in-changes-file unstable
E: pgbouncer: unstripped-binary-or-object usr/bin/pgbouncer

**Comment by PJMODOS** [comment] 2016-09-20 00:03
we don't make packages, those are build by postgres community, the debian package is part of postgres apt repo, maybe worth reporting this to there.

**Comment by markokr** [comment] 2016-12-19 17:33
Seems this was basically local build problem.  Closing.

**Closed by markokr** 2016-12-19 17:33 UTC

**Comment by zw963** [comment] 2017-03-08 18:33
I have same problem for my docker,  according this issue discuss, I fixed now.

this issue is caused by `evdns2`,  we need replace it with: libc-ares-dev
and  configure it with ``./configure --enable-evdns=no`` to use new `ares` 
resolve dns.

**Comment by ziggythehamster** [comment] 2017-10-16 22:01
FYI: The PGDG people changed something from 1.7.2-2 to 1.7.2-3 which caused this same issue for us (but I think they went from evdns2->c-ares). Here's a link to their ticket: https://redmine.postgresql.org/issues/2515

**Comment by kleptog** [comment] 2017-11-13 15:34
In ran into this today. It turns out that in docker hostname only resolves in the lower-case version. So if the service is called "foo" then "ping foo" works, but "ping FOO" doesn't.

Why does this matter? It looks like something inside pgbouncer (possibly evdns2) is changing the capitalisation randomly to increase the entropy of the DNS requests. If you strace pgbouncer you get the following:

```
sendto(6, "\315^\1\0\0\1\0\0\0\0\0\0\17tEsT-1-dATabAsE\0\0\1\0\1", 33, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, 16) = 33
sendto(6, "\256\353\1\0\0\1\0\0\0\0\0\0\17TEst-1-DatAbASe\0\0\34\0\1", 33, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, 16) = 33
```

The service it is trying to connect to is called "test-1-database", but it will never connect. I consider this a bug in Docker, but apparently disabling evdns2 (as noted above) will probably work around it.

**Comment by kleptog** [comment] 2017-11-13 15:52
I found a workaround: just before starting pgbouncer do:

```
# Docker doesn't understand case randomisation
echo "options randomize-case:0" >> /etc/resolv.conf
```

This tells evdns to not randomise the case, and everything works. Yay!

**Comment by kleptog** [comment] 2017-11-15 11:39
Got feedback from the Docker people that you can also add the `--dns-opt randomize-case:0` flag to `docker run` as well.

**Comment by jalberto** [comment] 2018-04-01 11:09
I am having this issue in pgb 1.8.1 with `c-ares` for DNS but not even the `randomize-case:0` workaround doesn't works.
a normal shell in the containr resolve the names properly.
