### ISSUE TITLE
Errors are sometimes swallowed.

### ISSUE THREAD

**Issue by i0rek** [pgbouncer/pgbouncer#30] opened 2014-08-29 13:25 UTC
Hello,

thank you very much for your work! PGBouncer helps us a lot!!
We are seing an issue though with errors being swallowed sometimes. I believe there have been similiar reports on the mailinglist:

1) http://lists.pgfoundry.org/pipermail/pgbouncer-general/2013-October/001158.html
2) http://lists.pgfoundry.org/pipermail/pgbouncer-general/2013-April/001127.html

Neither of them seem to have been fixed. I can reproduce the problem in our system and I would like to help track down that bug.

We are running PGBouncer 1.5.4 on Ubuntu

```
$ pgbouncer --version
pgbouncer version 1.5.4 (compiled by <buildd@roseapple> at 2013-06-18 17:16:50)
$ uname -mrs
Linux 3.13.0-24-generic x86_64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:   trusty
```

together with AWS RDS PostgreSQL 9.3.3.

I am running pgbouncer like that but that doesn't output anything while running the problematic query.

```
pgbouncer /etc/pgbouncer/pgbouncer.ini -v -v
```

and this is my config:

```
[databases]
test = host=test.rds.amazonaws.com user=test password=test dbname=test

[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
listen_addr = *
listen_port = 5432
unix_socket_dir = /var/run/postgresql
auth_type = trust
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction
server_reset_query =
ignore_startup_parameters = extra_float_digits
max_client_conn = 4096
default_pool_size = 1
min_pool_size = 1
server_idle_timeout = 0
```

There is no `.pgsqlrc`. The problem I am running into is that when inserting sometimes I get a unique constraint validation error and sometimes not. I am still working on narrowing down the problem as much I can. Is there anything that comes to your mind I can check?

**Comment by johto** [comment] 2015-01-29 23:08
What apps are you running against the pgbouncer instance?  I've tried a few things and I can't reproduce against the same build.

**Comment by oruen** [comment] 2015-02-02 07:21
@johto I'm running several Rails and Ruby apps.

**Comment by shtratos** [comment] 2016-08-06 13:36
Seeing this as well at pgbouncer version 1.7.2.
I run a Java app that uses Postgres JDBC driver to talk to postgres DB via pgbouncer.

I manage to reproduce it by doing INSERT that is expected to return a 23505 error ("duplicate key value violates unique constraint").
Sometimes it returns the expected error, sometimes it immediately responds with "Ready for query" (which causes a NullPointerException inside the driver, that's how I noticed it hapenning)
It doesn't happen every time, I have to repeat the same query up to 40 times to reproduce it.


I added `loglevel=2` to JDBC connection string and here's what I see in logs.
I've captured a tcpdump, it shows exactly the same thing as in logs, so there's no problem in a driver.

Here's example of normal behaviour:
```
17:42:25.319 (20) simple execute, handler=org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler@157eb205, maxRows=0, fetchSize=0, flags=81
17:42:25.319 (20)  FE=> Parse(stmt=null,query="/* ParticipantsDb.insert */ INSERT INTO participants (company_id, thread_id, referenced_id,
referenced_type, added_by_id) VALUES ($1, $2, $3, $4, $5) RETURNING *",oids={20,20,20,1043,20})
17:42:25.319 (20)  FE=> Bind(stmt=null,portal=null,$1=<1111>,$2=<12345>,$3=<56789>,$4=<'User'>,$5=<56789>)
17:42:25.319 (20)  FE=> Describe(portal=null)
17:42:25.319 (20)  FE=> Execute(portal=null,limit=0)
17:42:25.319 (20)  FE=> Sync
17:42:25.320 (20)  <=BE ParseComplete [null]
17:42:25.320 (20)  <=BE BindComplete [null]
17:42:25.320 (20)  <=BE RowDescription(6)
17:42:25.320 (20)         Field(,INT8,8,T)
17:42:25.320 (20)         Field(,INT8,8,T)
17:42:25.320 (20)         Field(,INT8,8,T)
17:42:25.320 (20)         Field(,INT8,8,T)
17:42:25.320 (20)         Field(,VARCHAR,65535,T)
17:42:25.320 (20)         Field(,INT8,8,T)
17:42:25.320 (20)  <=BE ErrorMessage(ERROR: duplicate key value violates unique constraint "participants_unique_participant_per_thread"
  Detail: Key (thread_id, referenced_id, referenced_type)=(12345, 56789, User) already exists.)
SQLException: SQLState(23505)
17:42:25.321 (20)  <=BE ReadyForQuery(I)
```

Here's an example of a bug:
```
17:42:25.967 (20) simple execute, handler=org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler@24548722, maxRows=0, fetchSize=0, flags=81
17:42:25.967 (20)  FE=> Parse(stmt=null,query="/* ParticipantsDb.insert */ INSERT INTO participants (company_id, thread_id, referenced_id,
referenced_type, added_by_id) VALUES ($1, $2, $3, $4, $5) RETURNING *",oids={20,20,20,1043,20})
17:42:25.967 (20)  FE=> Bind(stmt=null,portal=null,$1=<1111>,$2=<12345>,$3=<56789>,$4=<'User'>,$5=<56789>)
17:42:25.967 (20)  FE=> Describe(portal=null)
17:42:25.967 (20)  FE=> Execute(portal=null,limit=0)
17:42:25.967 (20)  FE=> Sync
17:42:25.968 (20)  <=BE ParseComplete [null]
17:42:25.969 (20)  <=BE BindComplete [null]
17:42:25.969 (20)  <=BE RowDescription(6)
17:42:25.969 (20)         Field(,INT8,8,T)
17:42:25.969 (20)         Field(,INT8,8,T)
17:42:25.969 (20)         Field(,INT8,8,T)
17:42:25.969 (20)         Field(,INT8,8,T)
17:42:25.969 (20)         Field(,VARCHAR,65535,T)
17:42:25.969 (20)         Field(,INT8,8,T)
17:42:25.969 (20)  <=BE ReadyForQuery(I)
```

Note that there's no error message after `RowDescription`.

**Comment by shtratos** [comment] 2016-08-06 13:42
Here are wireshark screenshots showing the sequence from TCP dump:
Normal behaviour:
<img width="689" alt="screen shot 2016-08-06 at 14 40 40" src="https://cloud.githubusercontent.com/assets/1232175/17457062/f156b026-5be3-11e6-8954-e149def8b134.png">

Bug:
<img width="687" alt="screen shot 2016-08-06 at 14 41 14" src="https://cloud.githubusercontent.com/assets/1232175/17457061/ee0f4658-5be3-11e6-989a-4f5ba6cc0be9.png">

**Comment by johto** [comment] 2016-08-06 14:23
@shtratos Interesting.  Any chance you could do a tcpdump of both `application -> pgbouncer` and `pgbouncer -> postgres` traffic while you're reproducing it?

**Comment by shtratos** [comment] 2016-08-06 18:59
To clarify: you want to confirm that this is pgbouncer fault and not postgres one? 
Or do you want to see exact packet sizes/contents?

We've got SSL between pgbouncer and postgres, so I'm not sure that would be very useful.
I'll see if we can try and disable SSL to collect forensics.

**Comment by tcrayford** [comment] 2017-01-07 12:27
Hi there,

Which version of Rails are y'all running? Earlier versions have a bug where they can set `client_min_messages` to `panic`, which disables most errors. Specifically you'll need a version with this PR merged: https://github.com/rails/rails/pull/22101

To the Java folk, are y'all doing anything similar? Setting `client_min_messages` from the application can be problematic.

**Comment by shtratos** [comment] 2017-01-09 16:14
Not in the Java app, but I suspect the pgbouncer connection might be shared with Rails app.

**Comment by DmitryBochkarev** [comment] 2017-08-31 13:34
We had the same problem, and installing `server_reset_query_always` in 1 helped solve this problem.
https://pgbouncer.github.io/config.html#connection-sanity-checks-timeouts

**Comment by petere** [comment] 2019-09-13 09:46
It looks like the last comment actually offered a plausible solution to this issue, so I'm going to close it.

**Closed by petere** 2019-09-13 09:46 UTC
