### ISSUE TITLE
Error when connecting -> launch_new_connection: last failed, wait

### ISSUE THREAD

**Issue by zam6ak** [pgbouncer/pgbouncer#211] opened 2017-06-07 21:16 UTC
Platform: `Windows Server 2012 64--bit`
PgBouncer: `pgbouncer 1.7.2, libevent 2.0.21-stable (win32), adns: evdns2, tls: OpenSSL 1.0.2k  26 Jan 2017`
PostgreSQL: `v9.6.2` (open source)

I installed PgBouncer using EDB's Stack Builder which downloaded v1.7.2-2, installed it and configured it.
PgBouncer and PostgreSQL are on the same server.

When I try to connect to default `postgres` databse using `postgres` user, PgBouncer goes into "loop" with same error message

Here is relevant section
```
...
2017-06-07 16:48:30.538 1940 NOISE C-02048FE0: (nodb)/(nouser)@[::1]:61636 pkt='!' len=87
2017-06-07 16:48:30.569 1940 DEBUG C-02048FE0: (nodb)/(nouser)@[::1]:61636 got var: user=postgres
2017-06-07 16:48:30.584 1940 DEBUG C-02048FE0: (nodb)/(nouser)@[::1]:61636 got var: database=postgres
2017-06-07 16:48:30.616 1940 DEBUG C-02048FE0: (nodb)/(nouser)@[::1]:61636 using application_name: psql
2017-06-07 16:48:30.647 1940 DEBUG C-02048FE0: (nodb)/(nouser)@[::1]:61636 got var: client_encoding=WIN1252
2017-06-07 16:48:30.678 1940 LOG C-02048FE0: postgres/postgres@[::1]:61636 login attempt: db=postgres user=postgres tls=no
2017-06-07 16:48:30.725 1940 NOISE resync: done=87, parse=87, recv=87
2017-06-07 16:48:30.741 1940 NOISE resync: done=0, parse=0, recv=0
2017-06-07 16:48:30.756 1940 NOISE C-02048FE0: postgres/postgres@[::1]:61636 pkt='p' len=41
2017-06-07 16:48:30.788 1940 DEBUG finish_client_login: no welcome message, pause
2017-06-07 16:48:30.803 1940 DEBUG C-02048FE0: postgres/postgres@[::1]:61636 pause_client
2017-06-07 16:48:30.834 1940 NOISE S-0207F248: postgres/postgres@(bad-af):0 inet socket: 127.0.0.1
2017-06-07 16:48:30.866 1940 DEBUG S-0207F248: postgres/postgres@127.0.0.1:5432 launching new connection to server
2017-06-07 16:48:30.913 1940 NOISE 
2017-06-07 16:48:30.913 1940 WARNING 
2017-06-07 16:48:30.928 1940 LOG S-0207F248: postgres/postgres@127.0.0.1:5432 closing because: connect failed (age=0)
2017-06-07 16:48:30.959 1940 NOISE failed to launch new connection
2017-06-07 16:48:30.991 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:31.084 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:31.428 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:31.772 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:32.116 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:32.459 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:32.803 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:33.147 1940 DEBUG launch_new_connection: last failed, wait
2017-06-07 16:48:33.491 1940 DEBUG launch_new_connection: last failed, wait
...
```

In the PostgreSQL log all I see is:
```
...
2017-06-07 16:48:30 EDT [2544]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1 LOG:  connection received: host=127.0.0.1 port=61637
2017-06-07 16:48:30 EDT [2544]: [2-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1 LOG:  incomplete startup packet
...
```

I am able to connect to `pgbouncer` database, but not much else.

**Comment by zam6ak** [comment] 2017-06-22 14:00
FYI
There is an alternative Windows binary download at http://winpg.jp/~saito/pgbouncer/
I don't get this error when I run the version of  PgBouncer from that site.... 
The distribution from above site does seem like it is statically linked (single EXE, and no additional DLLs), not sure if that matters or not, but it works...

**Comment by wibrt** [comment] 2017-12-07 13:08
the same error can be reproduced on debian

**Comment by petere** [comment] 2019-09-28 08:05
I'm going to close this since the original issue was solved by using a different Windows binary. The (possibly) faulty binary was not produced by us, so this is not an issue that is useful to track here. More concrete information on making the Windows port more robust is always welcome.

**Closed by petere** 2019-09-28 08:05 UTC
