### ISSUE TITLE
PgBouncer server blocked when slow queries hangs 

### ISSUE THREAD

**Issue by aek** [pgbouncer/pgbouncer#357] opened 2019-01-17 16:35 UTC
I have noticed that there is an strange behavior in PgBouncer server that get completely non-responsive. I have many applications connected to the PgBouncer server executing queries using pooling mode = transaction. I have noticed that there are moments when one of the applications are executing many concurrent queries that somehow get slow/hang in the postgres(visible in red in pgactivity, but not blocking or waiting queries, just red in the running queries list). 

Those queries from the same application somehow is blocking the rest of the applications queries making them completely unresponsive. After kill the application that have created the queries everything get back to normal and all the apps queries get responsive again. 

I have no idea why this could be happening and how to avoid it or resolve it. I could fix the application queries but also I need a way to isolate applications queries so it will not affect others applications queries in the same PgBouncer server.

Any clue?

**Comment by uspen** [comment] 2019-01-18 10:22
monitoring?
pool_size? Waiting clients?

**Comment by curlup** [comment] 2019-01-18 13:47
it might be due to exhaustion of one of the limits PgBouncer imposes upon number of concurrent connections. So it might be in some sense that PgBouncer is doing what it is designed for. 

You can check metrics in `show status` `show pools` etc. Check out this for more info https://blog.okmeter.io/use-red-and-real-world-pgbouncer-monitoring-61b34ebeebb8

A way to avoid this is to figure out which limit is causing this, and reconfigure you PgB and/or application that eats up all connections, in a way that this app server conns will be limited and there will be always free additional server connections to be used by other apps.

**Comment by achix** [comment] 2019-01-19 06:49
while that is happening did you check the actual locks in your DB?

**Comment by aek** [comment] 2019-01-21 11:16
I have checked about @curlup suggestions. Seems that I have used to set `default_pool_size = 180` and `reserve_pool_size = 15` to use 195 of 200 max_connections supported in the PostgreSQL server, while using a fallback connect string for around 100 databases/client apps allowing them for a max of 500 connections to PgBouncer Server due to the `max_client_conn` was set to `200000`.

I have wrongly taken the config default_pool_size config as a global setting for the PgBouncer server, not per database(since I just use fallback). After change it to the suggested value of 20 when using `pool_mode = transaction` everything seems to be back to normal, at least for now. I will continue to monitor this behavior trying to find out exactly what was be happening since this change could just be hiding the issue described that lead to a freeze PgBouncer server

**Comment by jcoleman** [comment] 2019-02-28 22:09
@aek Is this resolved? If so could you close the issue?

**Comment by aek** [comment] 2019-03-01 08:08
I have continued experiencing locks from queries of one database to queries on another databases. I don't have a clue of what could be causing the locks that affects other db connection pools even without a huge amount of query locks, the rest of the connections hang waiting for the query locks to resolve and I need to manually kill those queries backends using pg_activity

**Closed** 2019-09-13 14:53 UTC

**Comment by aek** [comment] 2019-09-13 16:27
@petere could you provide any clue about how this configuration or usage issue could be happening so we could avoid those scenarios or at least try to find a solution or an alternative usage?

**Comment by petere** [comment] 2019-09-16 07:33
AFAICT, you are using PgBouncer as intended. The purpose of PgBouncer is to funnel potentially many client connections into a limited number of server connections (= pool size). If there are more client connections than the pool size allows, the extra clients wait. There are many ways to configure and tune this, but it depends on the particular situation and what you are trying to achieve in the first place.

I suggest you use the chat room to find advice on usage and configuration.
