### ISSUE TITLE
Unable to connect to EDB-PostGreSQL

### ISSUE THREAD

**Issue by 00j** [pgbouncer/pgbouncer#161] opened 2016-11-07 23:23 UTC
Hi,

Please could you help? I'm sure there's a problem with PGBouncer when using the following configuration.

I've been testing this for the past few days and cannot get PGBouncer to connect with PostgreSQL

I had was a working system using PGBouncer 1.5, but on upgrading to 1.72 have not been able to get it to connect since.

PGBouncer was installed using EnterpriseDB Application Stack Builder

PG version 9.5 (also tested 9.6)
PGBouncer version 1.72

Tested on Windows 10, 7 and 2008 server.

For testing i'm using a very simple PHP script just to connect. EG:

host=127.0.0.1 dbname=postgres port=6432 user=postgres password=blabla

When running the above I get:

Unable to connect to PostgreSQL server: ERROR:  client_login_timeout (server down)
Unable to connect to PostgreSQL server: ERROR:  pgbouncer cannot connect to server

But if I swap port 6432 for 5432 and try again, the connection is successful.

**Here's an extract from the PGBouncer log:**

2016-11-07 22:12:52.913 12612 LOG File descriptor limit: -1 (H:-1), max_client_conn: 100, max fds possible: 230
2016-11-07 22:12:52.924 12612 LOG listening on ::/6432
2016-11-07 22:12:52.924 12612 LOG listening on 0.0.0.0:6432
2016-11-07 22:12:52.927 12612 LOG process up: pgbouncer 1.7.2, libevent 2.0.21-stable (win32), adns: evdns2, tls: OpenSSL 1.0.2g  1 Mar 2016
2016-11-07 22:13:09.223 12612 LOG C-01558FD8: postgres/postgres@127.0.0.1:60223 login attempt: db=postgres user=postgres tls=no
2016-11-07 22:13:09.225 12612 WARNING
2016-11-07 22:13:09.225 12612 LOG S-0158F240: postgres/postgres@127.0.0.1:5432 closing because: connect failed (age=0)
2016-11-07 22:13:24.299 12612 WARNING
2016-11-07 22:13:24.301 12612 LOG S-0158F240: postgres/postgres@127.0.0.1:5432 closing because: connect failed (age=0)
2016-11-07 22:13:39.317 12612 WARNING
2016-11-07 22:13:39.318 12612 LOG S-0158F240: postgres/postgres@127.0.0.1:5432 closing because: connect failed (age=0)
2016-11-07 22:13:52.924 12612 LOG Stats: 0 req/s, in 0 b/s, out 0 b/s,query 0 us
2016-11-07 22:13:54.338 12612 WARNING
2016-11-07 22:13:54.338 12612 LOG S-0158F240: postgres/postgres@127.0.0.1:5432 closing because: connect failed (age=0)
2016-11-07 22:14:09.353 12612 LOG C-01558FD8: postgres/postgres@127.0.0.1:60223 closing because: client_login_timeout (server down) (age=60)
2016-11-07 22:14:09.355 12612 WARNING C-01558FD8: postgres/postgres@127.0.0.1:60223 Pooler Error: client_login_timeout (server down)

Connecting to and validating with PGBouncer appears to be working fine, however the subsequent connection from PGBouncer to PostgreSQL fails.

I've checked the PostgreSQL logs but all that is listed is:

**PG Log**
2016-11-06 22:17:33 GMT LOG:  incomplete startup packet
2016-11-06 22:17:52 GMT LOG:  incomplete startup packet

I'm using the following PGBouncer config:

**pgbouncer.ini**

[databases]
postgres = host=127.0.0.1 port=5432
testdb = host=127.0.0.1 port=5432

[pgbouncer]
listen_addr = *
listen_port = 6432
auth_type = md5
auth_file = C:\Program Files\PgBouncer\etc\userlist.txt

the rest is standard and was not altered.

**PostgreSQL hba file**
host    all      all     127.0.0.1/32            md5
host    all     all     0.0.0.0    0.0.0.0     md5

PG is set to listen on all addresses.

I've exhausted any more configurations i can think of and have struggled to find anything meaningful via Google.

Thank you, regards
Jamie

**Comment by 00j** [comment] 2016-11-17 18:59
Hi,
I understand everyone's extremely busy, but please is there any quick suggestions i could investigate or perhaps more information that I can provide that helps?

**Comment by markokr** [comment] 2016-12-06 16:54
Are you using stock PostgreSQL or the EnterpriseDB variant?  pgbouncer does not use libpq, so if EDB has changed protocol then pgbouncer cannot connect to it indeed.

If stock one, then "incomplete startup packet" in weird.  Could you turn on pgbouncer verbose logging with "pgbouncer -v -v " and see if it logs anything interesting.

**Comment by markokr** [comment] 2016-12-27 15:50
The NOISE just means the log line is probably less interesting than DEBUG ones.

This snippet does not contain enough details why the connection failed.  Whats suspicios is that those details should appear behind the "launching" and "failed" lines:

2016-12-06 19:46:52.006 6524 DEBUG S-0082F240: postgres/postgres@127.0.0.1:5444 launching new connection to server
2016-12-06 19:46:52.029 6524 NOISE
2016-12-06 19:46:52.040 6524 WARNING
2016-12-06 19:46:52.046 6524 LOG S-0082F240: postgres/postgres@127.0.0.1:5444 closing because: connect failed (age=0)

Why are those 2 lines empty? did you edit it?  Was there any techical details about failure.
If not then they won't help us.

I assume EDB did not change protocol significantly, so the reason is probable that they have lot more or bigger internal params going on wire so there are places where pgbouncer might assume some packet can be sent or received with one-shot send()/recv() but cannot.

So the task is to find what packets cause the problem.

I suggest adding more log_info()-s to pgbouncer code around login traffic until you find out what the problem is.

**Comment by 00j** [comment] 2017-02-03 17:13
Hi Rajavelu,

Thanks for your post.

Can we assume your installation is not 'EDB-PostGreSQL' and is a stock PostgreSQL installation ?

Regards
Jamie

**Comment by Rajavelu** [comment] 2017-02-06 06:36
@00j Yes, We are not using EDB-PostgresSQL.

**Comment by malisper** [comment] 2017-03-15 00:30
I believe I've ran into this issue on Linux. I've repeatedly had an issue where writes to one pool will continuously fail with the message `Unable to connect to PostgreSQL server: ERROR: pgbouncer cannot connect to server`, while the other pools work fine.

**Comment by cb2109** [comment] 2017-06-12 10:49
@malisper if you have time to rebuild pgbouncer, can you see if my fix solves your bug too

**Comment by markokr** [comment] 2017-07-09 13:10
Should be fixed in master.

**Closed by markokr** 2017-07-09 13:10 UTC
Labels: feature, moreinfo
