### ISSUE TITLE
FATAL: in function put_in_order(): put_in_order: found existing elem

### ISSUE THREAD

**Issue by MichaelDBA** [pgbouncer/pgbouncer#502] opened 2020-07-12 12:48 UTC
Error is: FATAL @src/objects.c:312 in function put_in_order(): put_in_order: found existing elem

It happened while I was trying to log in with a user defined in userlist.txt.

I noticed this error has resulted in previous issues:
#41 
#250
#312
#314

Last few entries of log file:
```
2020-07-12 08:36:26.631 EDT [43248] LOG S-0x7f346732a5a8: connectdb_sit/infra_app_writer@unix:40543 closing because: server_lifetime (age=10650s)
2020-07-12 08:36:26.635 EDT [43248] LOG C-0x7f32b8: connectdb_sit/infra_app_writer@132.197.182.142:47984 login attempt: db=connectdb_sit user=infra_app_writer tls=no
2020-07-12 08:36:26.636 EDT [43248] LOG S-0x7f346732a5a8: connectdb_sit/infra_app_writer@unix:40543 new connection to server
2020-07-12 08:36:27.172 EDT [43248] LOG C-0x7f3728: connectdb_sit/infra_app_writer@132.197.182.153:44940 closing because: client close request (age=1776s)
2020-07-12 08:36:27.182 EDT [43248] LOG C-0x7f3728: connectdb_sit/infra_app_writer@132.197.182.153:47974 login attempt: db=connectdb_sit user=infra_app_writer tls=no
2020-07-12 08:36:41.625 EDT [43248] LOG C-0x7eca70: connectdb_sit/svcinv_app_reader@132.197.182.137:36452 closing because: client close request (age=1774s)
2c20-07-12 08:36:41.643 EDT [43248] FATAL @src/objects.c:312 in function put_in_order(): put_in_order: found existing elem

```

**Comment by petere** [comment] 2020-07-15 13:35
Can you reproduce it? What's your version and configuration?

**Comment by guybrowne** [comment] 2020-07-30 09:07
I just hit the same issue running on CentOS 7.8 with PostgreSQL 12.3

`2020-07-30 17:10:30.490 AEST [11669] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
2020-07-30 17:10:51.284 AEST [11669] FATAL @src/objects.c:312 in function put_in_order(): put_in_order: found existing elem

2020-07-30 17:24:02.157 AEST [4600] LOG kernel file descriptor limit: 1024 (hard: 4096); max_client_conn: 500, max expected fd use: 1562
2020-07-30 17:24:02.158 AEST [4600] LOG listening on 0.0.0.0:6432
2020-07-30 17:24:02.158 AEST [4600] LOG listening on unix:/tmp/.s.PGSQL.6432
2020-07-30 17:24:02.158 AEST [4600] LOG process up: PgBouncer 1.13.0, libevent 2.0.21-stable (epoll), adns: evdns2, tls: OpenSSL 1.0.2k-fips  26 Jan 2017
2020-07-30 17:24:16.805 AEST [4600] LOG C-0x55dafce957b0: pgbouncer/postgres@127.0.0.1:53722 login attempt: db=pgbouncer user=postgres tls=no
`

Haven't been able to reproduce due to this error after restarting the bouncer.  postgres user is the only account that can connect... its the only one in the userlist file.

`2020-07-30 17:39:02.159 AEST [4600] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
2020-07-30 17:39:33.042 AEST [4600] LOG C-0x55dafce957b0: (nodb)/(nouser)@10.240.86.153:35528 closing because: no such user: publish_event_etl_user (age=0s)
2020-07-30 17:39:33.042 AEST [4600] WARNING C-0x55dafce957b0: (nodb)/(nouser)@10.240.86.153:35528 pooler error: no such user: publish_event_etl_user
2020-07-30 17:39:33.042 AEST [4600] LOG C-0x55dafce957b0: (nodb)/(nouser)@10.240.86.153:35528 login failed: db=dcp_inventory_management user=publish_event_etl_user
2020-07-30 17:39:33.123 AEST [4600] LOG C-0x55dafce957b0: (nodb)/(nouser)@10.240.86.153:35532 closing because: no such user: publish_event_etl_user (age=0s)
2020-07-30 17:39:33.123 AEST [4600] WARNING C-0x55dafce957b0: (nodb)/(nouser)@10.240.86.153:35532 pooler error: no such user: publish_event_etl_user
2020-07-30 17:39:33.123 AEST [4600] LOG C-0x55dafce957b0: (nodb)/(nouser)@10.240.86.153:35532 login failed: db=dcp_inventory_management user=publish_event_etl_user
2020-07-30 17:40:02.159 AEST [4600] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
`

auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_user = postgres
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1
admin_users = postgres

**Comment by guybrowne** [comment] 2020-07-30 23:47
Had a thought overnight which may shed some more light.  Originally there was no [users] section defined in the config file just the following [databases] section.

`[databases]
dcp_dashboard = host=127.0.0.1 port=5433 pool_mode=transaction
dcp_inventory_management = host=127.0.0.1 port=5433 pool_mode=transaction
;; fallback connect string
* = host=127.0.0.1 port=5433`

Were having issues with the transaction pool mode for application but the user was connecting successfully, so added the users section.

`[users]
publish_event_etl_user = pool_mode=session max_user_connections=20`

A RELOAD command was issued.  First connection attempt using the publish_event_etl_user crashed the bouncer.

I then removed the [users] section from the configuration before restarting pgbouncer.  pgbouncer was restarted using the systemctl start command.

Now here is where I'm not sure if the issue is related... no users other than the postgres user defined in the userlist.txt file is able to connect to the database via the pgbouncer.  Here I get the (nodb)/(nouser)@... pooler error: no such user: publish_event_etl_user
Even users for the other defined database previously connecting now get this same message.

**Comment by jflambert** [comment] 2021-03-11 14:18
I'm getting this error with 1.15.0

**Comment by jflambert** [comment] 2021-07-16 03:21
@petere  here is my replication setup with 1.15.0

```
CREATE USER pgbouncer WITH PASSWORD 'pgbouncer';
CREATE SCHEMA IF NOT EXISTS pgbouncer AUTHORIZATION pgbouncer;

CREATE OR REPLACE FUNCTION pgbouncer.get_auth(p_usename TEXT)
RETURNS TABLE(username TEXT, password TEXT) AS
$$
BEGIN
    RAISE WARNING 'PgBouncer auth request: %', p_usename;

    RETURN QUERY
    SELECT usename::TEXT, passwd::TEXT FROM pg_catalog.pg_shadow
     WHERE usename = p_usename;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

REVOKE ALL ON FUNCTION pgbouncer.get_auth(p_usename TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION pgbouncer.get_auth(p_usename TEXT) TO pgbouncer;
```

```
/ $ cat /etc/pgbouncer/userlist.txt
"pgbouncer" "md5be5544d3807b54dd0637f2439ecb03b9"
```

```
/ $ cat /etc/pgbouncer/pgbouncer.ini
################## Auto generated ##################
[databases]
* = host=timescaledb port=5432 user=pgbouncer

[pgbouncer]
listen_addr = *
listen_port = 5432
unix_socket_dir =
user = postgres
auth_file = /etc/pgbouncer/userlist.txt
auth_type = md5
auth_user = pgbouncer
auth_query = SELECT username, password FROM pgbouncer.get_auth($1)
ignore_startup_parameters = extra_float_digits

# Log settings
log_stats = 0
verbose = 2
admin_users = postgres

# Connection sanity checks, timeouts

# TLS settings

# Dangerous timeouts
################## end file ##################
```

With an invalid user:

`WARNING C-0x7f13354580e0: postgres/(nouser)@192.168.240.1:44336 pooler error: no such user`

With a valid user:

`FATAL @src/objects.c:312 in function put_in_order(): put_in_order: found existing elem`

**Comment by jflambert** [comment] 2021-07-16 03:31
Even simpler. I get the same problem using postgres/postgres and the following auth_query

`SELECT usename, passwd FROM pg_shadow WHERE usename=$1`

**Comment by 2tvenom** [comment] 2021-07-29 14:07
I had same problem. Ok with this config

`[databases]
* = host=postgres auth_user=pgbouncer

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 5432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_query = SELECT username, password FROM pgbouncer.get_auth($1)
admin_users = postgres, pgbouncer
stats_users = postgres, pgbouncer
pool_mode = transaction
server_reset_query = DISCARD ALL
ignore_startup_parameters = extra_float_digits`

in userlist.txt only pgbouncer credentials

**Comment by guybrowne** [comment] 2021-07-30 00:46
@jflambert Please correct me if wrong but are you trying to force all database connections to user pgbouncer account or authenticate with pgbouncer account?

`################## Auto generated ##################
[databases]
* = host=timescaledb port=5432 user=pgbouncer`

The above is forcing all connections to connect as pgbouncer otherwise parameter should be auth_user=pgbouncer
Otherwise my understanding and usage of these parameters is wrong. :)

**Comment by jflambert** [comment] 2021-08-05 01:58
Thank you @guybrowne looks like I was overthinking it.

So I was triggering the same error message as you, but it looks like the blame was on me.

**Comment by justinpryzby** [comment] 2021-10-04 03:37
I also hit this issue after sending HUP while attempting to use the [users] section (which also doesn't work).
Is there still more info needed ?

**Comment by moreinhardt** [comment] 2022-02-01 11:31
The same issue has been happening to me with version 1.16.1, just following the instructions from the documentation.

The related settings from `pgbouncer.ini`:
```
[pgbouncer]
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_user = pgbouncer
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1
admin_users = pgbouncer
stats_users = pgbouncer
```
Then running

```
psql -p 6432 pgbouncer
```

As the same system user running pgbouncer (`postgres`).

This crash happened *every time I ran this*.

**I managed to get it to work** by running `psql -p 6432 pgbouncer pgbouncer` which actually specifies the database *and* the user instead of just the database :thinking: 

```
SYNOPSIS
       psql [option...] [dbname [username]]
```

Does this mean it just needs an update to the docs?

**Comment by rafaelthca** [comment] 2022-02-22 01:56
Bug appears when pgbouncer is configured with `auth_user`, where in that case no users are needed in the `auth_file` (note that the [users] section is commented out):

```
[databases]
postgres = host=127.0.0.1 port=5432 dbname=postgres pool_mode=transaction auth_user=pgbouncer

[pgbouncer]
default_pool_size=18
listen_addr = *
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1
admin_users = pgbouncer
stats_users = pgbouncer
application_name_add_host = 1
ignore_startup_parameters = extra_float_digits
max_client_conn = 3000
query_wait_timeout=30
stats_period = 60
verbose = 0

;[users]
;postgres = pool_mode=session
```

Starting pgbouncer and looking stats:

```
pgbouncer=# show pools;
 database  |   user    | cl_active | cl_waiting | sv_active | sv_idle | sv_used | sv_tested | sv_login | maxwait | maxwait_us | pool_mode 
-----------+-----------+-----------+------------+-----------+---------+---------+-----------+----------+---------+------------+-----------
 pgbouncer | pgbouncer |         1 |          0 |         0 |       0 |       0 |         0 |        0 |       0 |          0 | statement
(1 row)

pgbouncer=# show users;
   name    | pool_mode 
-----------+-----------
 pgbouncer | 
(1 row)
```

That makes sense, only pgbouncer user is configured and a single pool. If I now try to connect as postgres and check pgbouncer stats again:

```
postgres@rafaelthca:/etc/pgbouncer$ psql -p 6432 -U postgres postgres -h 127.0.0.1
Password for user postgres: 
postgres@rafaelthca:/etc/pgbouncer$ psql -p 6432 -U pgbouncer pgbouncer -h /tmp
psql (12.9 (Ubuntu 12.9-0ubuntu0.20.04.1), server 1.14.0/bouncer)
Type "help" for help.

pgbouncer=# show pools;
 database  |   user    | cl_active | cl_waiting | sv_active | sv_idle | sv_used | sv_tested | sv_login | maxwait | maxwait_us |  pool_mode  
-----------+-----------+-----------+------------+-----------+---------+---------+-----------+----------+---------+------------+-------------
 pgbouncer | pgbouncer |         1 |          0 |         0 |       0 |       0 |         0 |        0 |       0 |          0 | statement
 postgres  | pgbouncer |         0 |          0 |         0 |       1 |       0 |         0 |        0 |       0 |          0 | transaction
 postgres  | postgres  |         0 |          0 |         0 |       0 |       0 |         0 |        0 |       0 |          0 | transaction
(3 rows)

pgbouncer=# show users;
   name    | pool_mode 
-----------+-----------
 pgbouncer | 
(1 row)
```

What we see there is a pool belonging to postgres user, but that user is not a pgbouncer client user.

Now we uncomment the [users] section and reload pgbouncer. Checking the stats:

```
pgbouncer=# show pools;
 database  |   user    | cl_active | cl_waiting | sv_active | sv_idle | sv_used | sv_tested | sv_login | maxwait | maxwait_us |  pool_mode  
-----------+-----------+-----------+------------+-----------+---------+---------+-----------+----------+---------+------------+-------------
 pgbouncer | pgbouncer |         1 |          0 |         0 |       0 |       0 |         0 |        0 |       0 |          0 | statement
 postgres  | pgbouncer |         0 |          0 |         0 |       0 |       1 |         0 |        0 |       0 |          0 | transaction
 postgres  | postgres  |         0 |          0 |         0 |       0 |       0 |         0 |        0 |       0 |          0 | transaction
(3 rows)

pgbouncer=# show users;
   name    | pool_mode 
-----------+-----------
 pgbouncer | 
 postgres  | session
(2 rows)
```

We now have a pgbouncer client user for `postgres` but that pre-existing pool with (postgres/postgres) does not belong to it. We can see by the pool_mode columns that don't match.

If we now try to connect as postgres:

```
postgres@rafaelthca:/etc/pgbouncer$ psql -p 6432 -U postgres postgres -h 127.0.0.1
psql: error: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Error in log:

```
2022-02-21 22:48:10.920 -03 [33646] FATAL @src/objects.c:312 in function put_in_order(): put_in_order: found existing elem
```

Bug very likely comes from here:

```
/* create new pool object */
static PgPool *new_pool(PgDatabase *db, PgUser *user)
{
	PgPool *pool;

	pool = slab_alloc(pool_cache);
	if (!pool)
		return NULL;

	list_init(&pool->head);
	list_init(&pool->map_head);

	pool->user = user;
	pool->db = db;

	statlist_init(&pool->active_client_list, "active_client_list");
	statlist_init(&pool->waiting_client_list, "waiting_client_list");
	statlist_init(&pool->active_server_list, "active_server_list");
	statlist_init(&pool->idle_server_list, "idle_server_list");
	statlist_init(&pool->tested_server_list, "tested_server_list");
	statlist_init(&pool->used_server_list, "used_server_list");
	statlist_init(&pool->new_server_list, "new_server_list");
	statlist_init(&pool->cancel_req_list, "cancel_req_list");

	list_append(&user->pool_list, &pool->map_head);

	/* keep pools in db/user order to make stats faster */
	put_in_order(&pool->head, &pool_list, cmp_pool);

	return pool;
}
```

```
/* find pool object, create if needed */
PgPool *get_pool(PgDatabase *db, PgUser *user)
{
	struct List *item;
	PgPool *pool;

	if (!db || !user)
		return NULL;

	list_for_each(item, &user->pool_list) {
		pool = container_of(item, PgPool, map_head);
		if (pool->db == db)
			return pool;
	}

	return new_pool(db, user);
}
```

The `get_pool` attempts to find a pool for postgres user and doesn't find it, because
the postgres user was created after the reload with an empty list of pools. Then `new_pool`
is called and will trigger the bug, as a lingering pool for the same dbname/username exists.

**Comment by petere** [comment] 2022-02-22 08:14
I think this is the same underlying problem as https://github.com/pgbouncer/pgbouncer/issues/314#issuecomment-1042807960.

**Closed** 2024-08-01 17:34 UTC
