### ISSUE TITLE
pgbouncer high cl_waiting and low cl_active、sv_active

### ISSUE THREAD

**Issue by Aken-Gan** [pgbouncer/pgbouncer#506] opened 2020-07-17 03:34 UTC
I try to saturate the server using pgbouncer with the pool_mode=transaction.

I was running a Select-only test, with 48 clients for 5 minutes. 
During the test:
* pgbouncer、pg node load are all  low，CPU used low than 30%. 
* SHOW POOLS tells that cl_active is only about 5, and all the rest is cl_waiting.
* number of sv_active is very low (2-3).

So it looks like pgbouncer cannot spawn enough parallel server sessions?
Can this be pgbouncer, postgres or kernel parameters issue?

Thanks

**Comment by petere** [comment] 2020-07-21 20:19
What is your pool size setting for this test?

**Comment by Aken-Gan** [comment] 2020-07-23 07:02
$ egrep -e "pool_size|max|pool_mode" $PGDATA/pgbouncer.ini | grep -v "^;"
pool_mode = transaction
max_client_conn = 1900
default_pool_size = 96 
min_pool_size = 32
max_db_connections = 512
max_user_connections =512

**Comment by Aken-Gan** [comment] 2020-07-23 07:02
$ egrep -e "pool_size|max|pool_mode" $PGDATA/pgbouncer.ini | grep -v "^;"
pool_mode = transaction
max_client_conn = 1900
default_pool_size = 96
min_pool_size = 32
max_db_connections = 512
max_user_connections =512

**Comment by eulerto** [comment] 2020-08-02 00:30
I cannot reproduce your problem. Are you using `pgbench`? Are you sure it is a select only test (`pgbench -S`)? Could you provide 3 `show pools` output during your test?

**Comment by chobostar** [comment] 2020-10-19 09:03
@Aken-Gan do you use cancel requests in your code? (or your driver)
here related promblem is solved:
https://habr.com/ru/company/avito/blog/519610/

**Comment by chobostar** [comment] 2020-10-19 09:05
@eulerto here is reproduce: https://github.com/iosadchiy/pgx_pgbouncer_issue

**Comment by jcoleman** [comment] 2021-07-09 18:59
Is it possible this is fixed with https://github.com/pgbouncer/pgbouncer/commit/bfafe67ce084cea479826444fcadcf4771eac0b1 and https://github.com/pgbouncer/pgbouncer/commit/b477fc1599f82abd80faef09ab4d782270c69e03?

**Closed** 2021-11-23 17:40 UTC
Labels: pending-close
